### ISSUE TITLE
Recorded History

### ISSUE THREAD

**Issue by rbray-lilly** [keyteki/keyteki#3326] opened 2023-06-22 02:39 UTC
Log did not display the card that was revealed to be archived. In this instance only one card was archived.

**Comment by strib** [comment] 2023-06-22 02:40
Duplicate of https://github.com/keyteki/keyteki/issues/3313 and #3325  -- already fixed in the code, pending the next deploy.

**Comment by cryogen** [comment] 2023-06-22 12:10
Deployed

**Closed by cryogen** 2023-06-22 12:10 UTC
Labels: duplicate
