### ISSUE TITLE
Outnegotiate counting all types of pips for effect

### ISSUE THREAD

**Issue by DylanGranger** [keyteki/keyteki#3340] opened 2023-06-22 14:35 UTC
![image](https://github.com/keyteki/keyteki/assets/34193643/f1644cbd-f7ca-4b55-95fa-930e33ed531c)

Outnegotiate targeted a Lethologica with its regular amber pip alongside a damage and draw pip, and incorrectly stole 3 amber.

Game log:
Fabulosing brings 嚴酷的月亮戰略家​尼莫 to The Crucible
Fabulousing brings Ypsu the Terribly Avaricious to The Crucible
Fabulosing won the flip and is first player
 Fabulousing has connected to the game server
 Fabulosing has connected to the game server
Fabulosing is shuffling their deck
Fabulosing draws 6 card  s to their maximum of 6
Fabulousing is shuffling their deck
Fabulousing draws 6 card  s to their maximum of 6
Fabulosing draws 1 card 
Key phase - Fabulosing
Fabulosing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses untamed  as their active house this turn
Main phase - Fabulosing
Fabulosing plays Commune
Fabulosing uses Commune to lose all their Æmber  and gain 4 Æmber 
Fabulosing played Commune which has Omega, ending this step
Ready phase - Fabulosing
Draw phase - Fabulosing
End of turn 1
Fabulosing: 4 Æmber  (0 keys) Fabulousing: 0 Æmber  (0 keys)
TURN 1 - Fabulousing
Key phase - Fabulousing
Fabulousing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulousing
Fabulousing chooses saurian  as their active house this turn
Main phase - Fabulousing
Fabulousing discards Crushing Charge
Fabulousing discards Crushing Charge
Fabulousing plays Imperator Drusilla
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
Fabulousing draws 3 card  s to their maximum of 6
End of turn 1
Fabulosing: 4 Æmber  (0 keys) Fabulousing: 0 Æmber  (0 keys)
TURN 2 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses untamed  as their active house this turn
Main phase - Fabulosing
Fabulosing plays Niffle Grounds
Fabulosing gains an Æmber  due to Niffle Grounds's bonus icon
Fabulosing deals 1 damage to Imperator Drusilla due to Niffle Grounds's bonus icon
Fabulosing plays Pismire
Ready phase - Fabulosing
Fabulosing readies their cards 
Draw phase - Fabulosing
Fabulosing draws 2 card  s to their maximum of 6
End of turn 2
Fabulosing: 5 Æmber  (0 keys) Fabulousing: 0 Æmber  (0 keys)
TURN 2 - Fabulousing
Key phase - Fabulousing
Fabulousing does not forge a key. They have 0 amber. The current cost is 8 Æmber 
House phase - Fabulousing
Fabulousing chooses saurian  as their active house this turn
Main phase - Fabulousing
Fabulousing uses Imperator Drusilla to make Imperator Drusilla fight Pismire
Fabulousing plays Arm the Plebeians
Fabulousing gains an Æmber  due to Arm the Plebeians's bonus icon
Fabulousing uses Arm the Plebeians to make a token creature
Fabulousing plays Arm the Plebeians
Fabulousing gains an Æmber  due to Arm the Plebeians's bonus icon
Fabulousing uses Arm the Plebeians to make a token creature
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
Fabulousing draws 2 card  s to their maximum of 6
End of turn 2
Fabulosing: 5 Æmber  (0 keys) Fabulousing: 2 Æmber  (0 keys)
TURN 3 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses logos  as their active house this turn
Main phase - Fabulosing
Fabulosing plays Lethologica
Fabulosing gains an Æmber  due to Lethologica's bonus icon
Fabulosing deals 1 damage to Bellatoran Warrior due to Lethologica's bonus icon
Bellatoran Warrior's ward token prevents the damage dealt by a bonus icon and is discarded
Fabulosing draws a card  due to Lethologica's bonus icon
Fabulosing uses Lethologica to discard Seeker Needle and [REDACTED]
Fabulosing takes [REDACTED] into their hand
Fabulosing plays Infomorph
Fabulosing deals 1 damage to Bellatoran Warrior due to Infomorph's bonus icon
Bellatoran Warrior's ward token prevents the damage dealt by a bonus icon and is discarded
Fabulosing draws a card  due to Infomorph's bonus icon
Fabulosing plays [REDACTED]
Fabulosing plays Infomorph
Ready phase - Fabulosing
Fabulosing readies their cards 
Draw phase - Fabulosing
Fabulosing draws 1 card  to their maximum of 6
 Fabulosing declares Check!
End of turn 3
Fabulosing: 6 Æmber  (0 keys) Fabulousing: 2 Æmber  (0 keys)
TURN 3 - Fabulousing
Key phase - Fabulousing
Fabulousing does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Fabulousing
Fabulousing chooses ekwidon  as their active house this turn
Main phase - Fabulousing
Fabulousing plays Outnegotiate
Fabulousing gains an Æmber  due to Outnegotiate's bonus icon
Fabulousing uses Outnegotiate to steal 3 Æmber  from Fabulosing
Fabulousing uses Outnegotiate to return Lethologica to the bottom of their owner's deck

**Comment by romanogit** [comment] 2023-06-23 20:25
Dupe of https://github.com/keyteki/keyteki/issues/3340

**Closed by romanogit** 2023-06-23 20:25 UTC
Labels: duplicate
