### ISSUE TITLE
Multiple Sir Marrows each capture an amber instead of offering a choice

### ISSUE THREAD

**Issue by Kalythmos** [keyteki/keyteki#190] opened 2019-07-29 23:21 UTC
When 2 Sir Marrows are in play in opponent side, and the I reap, I could decide which take the aember, but both take 1 aember. I think it is a bug.
I think in real game, I decide which take and the other wouldnt.

**Comment by Achocholacek** [comment] 2019-07-30 03:42
Definitely an edge case we didn't consider - need to review placeAmber method as I don't believe it allows for conditional targeting (at least it doesn't appear to in my various tests)

**Comment by jelyman01** [comment] 2019-09-30 20:12
still an issue...Multiple Marrows capture one each upon opponent reaping

**Comment by cryogen** [comment] 2019-09-30 20:14
The issue is still open and no fix has been submitted, so it’s not surprising it’s still happening :)

**Closed** 2020-12-04 13:10 UTC
Labels: Timing Refactor, bug
