### ISSUE TITLE
1-2 Punch stuns all creatures

### ISSUE THREAD

**Issue by heiligeremilius** [keyteki/keyteki#103] opened 2019-07-28 10:42 UTC
After playing 1-2 Punch all creatures are stunned. It should only be the one, selected by the active player.

**Comment by issa** [comment] 2019-07-28 10:45
Duplicate of #81

**Comment by cryogen** [comment] 2019-07-28 10:49
Thanks for the report, as @issa says, this is a duplicate, so closing this one!

**Closed by cryogen** 2019-07-28 10:49 UTC
