### ISSUE TITLE
Bug for MM deck. Too many cards.

### ISSUE THREAD

**Issue by gorebellyph** [keyteki/keyteki#2540] opened 2021-04-26 04:51 UTC
Hi I tried uploading an MM deck but it displayed too many cards than 30.
![Untitled](https://user-images.githubusercontent.com/83200368/116030287-d0495b00-a68d-11eb-92c8-63d695f17bd2.jpg)

**Comment by romanogit** [comment] 2021-04-26 11:47
Dupe of #2538 
Can you delete and import again? Thank you. It has been fixed.

**Closed by romanogit** 2021-04-26 11:47 UTC
