### ISSUE TITLE
Omnipus bugs.  Reap effect and play extra cards 

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#2503] opened 2021-04-19 15:54 UTC
[omnipus.txt](https://github.com/keyteki/keyteki/files/6337419/omnipus.txt)
![omnipus_reap](https://user-images.githubusercontent.com/6394071/115266331-f9e20f80-a0ec-11eb-8ea4-b3baa1492b9b.PNG)

My opponent played an Omnipus when I had an ember imp out and played 2 Tentaclid after discarding them and another creature. This seems like it should be handled the same way Wild Wormhole works if it was the second card played in the turn.  

later my opponent reaped with Omnipus and then they lost all their aember.  We were also unable to fix in manual mode.  
Chat log at this point read 
```
uses Omnipus to lose [object Object],[object Object] Æmber 
```

**Comment by cryogen** [comment] 2021-04-19 15:56
Duplicate of #2428

**Comment by agrandstudent** [comment] 2021-04-19 16:16
Looking at the fixes in e0889dbc99a434342394b2c3966f2177439cd29e there is still the ember imp bug that wont be fixed.  The Tentaclid are still being put into play instead of played.

**Comment by romanogit** [comment] 2021-04-19 16:33
Reopening to implement it as `play` instead of `put into play`

**Comment by romanogit** [comment] 2021-04-20 10:51
Deployed

**Closed by romanogit** 2021-04-20 10:51 UTC
Labels: Pending Deploy
