### ISSUE TITLE
Exchange Offier off house in alliance deck

### ISSUE THREAD

**Issue by RogueUrsa** [keyteki/keyteki#3488] opened 2023-09-22 17:21 UTC
I created an alliance deck of logos, saurian and untamed. the logos house had exchange officer in it. TCO made the exchange officer a 'sanctum' card in my deck while playing (shows it in logos on archon). gladly came out at end of game so only affected a couple of turns..

**Comment by RogueUrsa** [comment] 2023-09-22 17:25
On investigation, Exchange Officer appears in one of the other decks in the alliance in house sanctum, so perhaps that is the issue - it 'found' that exchange officer first and added it to the deck instead of the one in logos. (so probably something to do with how your alliance algorithm is pulling the cards from the decks). :)

**Comment by RogueUrsa** [comment] 2023-09-22 17:26
to be clear the deck which i pull saurian house from has the sanctum exchange officer

**Comment by RogueUrsa** [comment] 2023-09-22 17:30
if it helps to reproduce the bug, the decks were loaded so that i would have on display list untamed deck at top, then saurian then logos, so i would have clicked untamed, then saurian, then logos to 'build' the alliance. (i.e. logos deck was first imported  to TCO, then saurian then untamed).    
Just trying to think of all possible algorithmic permutations that might help you source the error.

**Comment by RogueUrsa** [comment] 2023-09-22 17:34
okay, so i tried to 'select' the house in reverse order - chosing logos first, the exchange officer still comes out sanctum, so it isn't the order of selecting the pods that causes the bug

**Comment by romanogit** [comment] 2023-10-03 04:05
Dupe of https://github.com/keyteki/keyteki/issues/2875

**Closed by romanogit** 2023-10-03 04:05 UTC
Labels: alliance
