### ISSUE TITLE
Aember on Senator Shrix doesn't let me forge

### ISSUE THREAD

**Issue by Dunkoro** [keyteki/keyteki#909] opened 2019-11-14 08:52 UTC
https://prnt.sc/pwr92a

Had a total of 6 aember on Senators, no aember in pool, 6 key cost and didn't forge at beginning of turn.

**Comment by cryogen** [comment] 2019-11-14 09:00
Thanks for reporting!  This is a duplicate of #518

**Closed by cryogen** 2019-11-14 09:00 UTC
