### ISSUE TITLE
Mimicry grafted onto Infomancer didn't trigger when I reaped

### ISSUE THREAD

**Issue by OzOhM** [keyteki/keyteki#935] opened 2019-11-16 10:30 UTC
Is it a normal behaviour? Mimicry doesn't indeed have a "Play:" effect

**Comment by Aureliaar** [comment] 2019-11-16 11:51
That's what should happen, yes. 
Grafted cards only trigger the play effect, thereby skipping other parts of the card - like Alpha\Omega, or the entire text in Mimicry's case

**Comment by cryogen** [comment] 2019-11-16 11:54
Correct.  Mimicry is a 'when you play' rather than a 'Play:' so it does not trigger from Infomancer.  Not a bug, so closing.  Thanks for reporting!

**Closed by cryogen** 2019-11-16 11:54 UTC
