### ISSUE TITLE
Sir Marrows reap probelm

### ISSUE THREAD

**Issue by Avatar-of-Chaos** [keyteki/keyteki#1333] opened 2020-04-23 00:51 UTC
When Sir Marrows is on the board, any reap counts as EVERY Sir Marrows obtaining an aember, when the option for only ONE Sir Marrows should be available when multiple Sir Marrows are on the board. Otherwise, new aember is introduced where it shouldn't be.

**Comment by romanogit** [comment] 2020-04-24 02:07
@Avatar-of-Chaos ,
this is a known issue and very difficult to fix.
It is a dupe of https://github.com/keyteki/keyteki/issues/190

**Closed by romanogit** 2020-04-24 02:07 UTC
