### ISSUE TITLE
Strange Shell didn't have any armor.

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#3324] opened 2023-06-22 00:35 UTC
Multiple games, Strange Shell token getting killed by 1 damage pings.

**Comment by kensterel** [comment] 2023-06-22 00:45
Dupe of https://github.com/keyteki/keyteki/issues/3300

Pending deploy... wait a bit...

**Comment by cryogen** [comment] 2023-06-22 12:10
Deployed

**Closed by cryogen** 2023-06-22 12:10 UTC
Labels: duplicate
