### ISSUE TITLE
WOE: Befuddle should have an alert notification

### ISSUE THREAD

**Issue by kensterel** [keyteki/keyteki#3321] opened 2023-06-21 23:52 UTC
Most cards that restrict the opponents actions on their next turn have an alert highlighting the action. It would be nice if Befuddle had the same thing so it is easier to spot.

**Comment by romanogit** [comment] 2023-06-21 23:54
Dupe of https://github.com/keyteki/keyteki/issues/3282

Pending deploy... wait a bit...

**Closed by romanogit** 2023-06-21 23:54 UTC
