### ISSUE TITLE
bugs in card use ( I think)

### ISSUE THREAD

**Issue by scyco** [keyteki/keyteki#853] opened 2019-11-11 10:37 UTC
Hi,
during my last game I faced this problem:
- my opponent played inky gloom that avoid me to play creatures
- in my turn I selesct Star alliance and would like to play CALV-1N as an upgrade card but I cannot.

Is it a bug or not?
thanks a lot

**Comment by romanogit** [comment] 2019-11-13 07:31
Inky Gloom prevent opponents from reaping.
Maybe he used Lifeward?

**Comment by saluk** [comment] 2019-11-13 18:06
Lifeward + star alliance creature-upgrades is probably a bug here. You are playing it as an upgrade INSTEAD of a creature. I think we prevent playing the card before the code changes the card into an upgrade (I did that one... oops).

**Comment by scyco** [comment] 2019-11-14 08:59
> Inky Gloom prevent opponents from reaping.
> Maybe he used Lifeward?

yes it was Lifeward ;-)

**Comment by romanogit** [comment] 2020-04-17 14:13
Dupe of #938 and #966

**Closed by romanogit** 2020-04-17 14:13 UTC
