### ISSUE TITLE
Bordan the Remdeemed

### ISSUE THREAD

**Issue by Herzbube76** [keyteki/keyteki#199] opened 2019-07-30 12:23 UTC
Couldnt choose the action of Bordan, only fight and reap.

**Comment by Achocholacek** [comment] 2019-07-30 15:02
Cannot reproduce this locally - do you remember anything else about board state at the time?

**Comment by Herzbube76** [comment] 2019-07-31 02:13
Sorry no. Tried it 2 turns. Both turns didnt work.

**Comment by Achocholacek** [comment] 2019-08-01 22:31
Closing this for now - if issue reoccurs please open a new ticket with as much data as possible!

**Closed by Achocholacek** 2019-08-01 22:31 UTC
Labels: bug, unable to reproduce
