### ISSUE TITLE
Flaxia had an incorrect "Use this card's Action ability" option

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#289] opened 2019-08-07 12:00 UTC
My Deck: https://www.keyforgegame.com/deck-details/50195fac-c336-46c4-ad10-32fffd373fe5
Opponent's Deck: https://www.keyforgegame.com/deck-details/165583eb-f720-457f-bb6d-2580fcef5e7c

I played `Flaxia` as my first game card. 

Opponent played `Skybooster Squadron` and `Mindworm`. Then he played a `Containment Field`, attaching it to `Flaxia`.

When I selected `Flaxia`, game showed options to Reap, Fight and Use Action, but Flaxia has no Action.
 
![image](https://user-images.githubusercontent.com/2104075/62621097-7325d880-b8f1-11e9-878e-50ec238e3a13.png)

![image](https://user-images.githubusercontent.com/2104075/62621076-66a18000-b8f1-11e9-9bf6-5011b4981582.png)

**Comment by Achocholacek** [comment] 2019-08-07 13:34
This is a known issue with Containment field that is being worked on! (Duplicate of #268 )

**Closed by Achocholacek** 2019-08-07 13:34 UTC
Labels: duplicate
