### ISSUE TITLE
Rad Penny and Pile of Skulls loop?

### ISSUE THREAD

**Issue by Piix98** [keyteki/keyteki#2074] opened 2020-11-23 14:13 UTC
While playing I got stuck in the prompt selection.

The opponent had two rad penny on the board and I had a pile of skulls.
I played red alert, destroying 5 of the opponent's creatures, among which there were the 2 rad pennys. The game let me capture for the other 3 creatures quite easily, but since the rad pennys were back in the deck, I couldn't select them to capture two other ambers. This got me in a loop where I couldn't click anything except for the "back" button, and if I clicked on it,  I couldn't select anything except for the pile of skull, entering in an endless loop.

I have "Prompt to order simultaneous abilities" on, so maybe it's only my fault, but i couldn't play the game anymore, even by trying to switch in manual mode

**Comment by romanogit** [comment] 2020-12-04 16:22
This is a dupe of https://github.com/keyteki/keyteki/issues/1929 Keeping just one opened.

**Closed by romanogit** 2020-12-04 16:22 UTC
