### ISSUE TITLE
Incorrect icons in Archon card (deck list)

### ISSUE THREAD

**Issue by Gimu87** [keyteki/keyteki#2466] opened 2021-04-17 13:51 UTC
The symbols of actions and artifacts are swapped.
eg: COTA 054 - Arise
COTA 075 -  Lash of Broken Dreams
![image](https://user-images.githubusercontent.com/53396189/115115416-a8267180-9f94-11eb-85aa-51dc11af5396.png)

**Comment by romanogit** [comment] 2021-04-17 13:53
This one is already fixed, waiting for deploy

**Comment by SkyJedi** [comment] 2021-04-17 13:55
Dupe of #2441

**Closed by SkyJedi** 2021-04-17 13:55 UTC
Labels: duplicate
