### ISSUE TITLE
Poltergeist on opponent's golden spiral made player exalt and use one of the opponent's creatures

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1579] opened 2020-06-13 00:39 UTC
I didn't think to copy the log because I was just spectating but this happened in a game 

A player played poltergeist to use opponent's golden spiral. The player who played poltergeist had no friendly creatures in play at that point. He was prompted to choose one of his opponent's creatures, so he exalted and reaped with their questor jarta. What should have happened is that the action ability of the spiral should have fizzled. The spiral should have just been destroyed.

**Comment by jeremylarner** [comment] 2020-06-13 08:49
I can't replicate this, Poltergeist/The golden Spiral seems to work fine in all my tests.  Was there anything else on the board which might have caused it?

**Comment by hydrophilic-attack** [comment] 2020-06-13 15:46
It's possible I misremembered the details. The opponent of the player of the poltergeist had a sneklifter in their deck, and had earlier on taken over the poltergeist player's dominator bauble. It's possible that poltergeist player tried to use the dominator bauble that they owned, but which the opponent at that time controlled, rather than their golden spiral and that this caused the bug where they had to use their opponent's creature. That's the only other possibility I can think of

**Comment by jeremylarner** [comment] 2020-06-14 10:53
Huh.... I'll try that - that sounds a more plausible source of the bug

**Comment by jeremylarner** [comment] 2020-06-14 11:06
Nope can't get sneklifted Dominator bauble to misbehave either :(

**Comment by romanogit** [comment] 2021-06-30 20:03
Unable to reproduce. It is very likely that this was fixed with the event refactor PRs

**Closed by romanogit** 2021-06-30 20:03 UTC
Labels: unable to reproduce
