### ISSUE TITLE
DT Omnipus effects not applyed

### ISSUE THREAD

**Issue by Gimu87** [keyteki/keyteki#2468] opened 2021-04-17 14:00 UTC
I have 4 card in the deck.
Plaing Omnipus nothing appears.

Expected result:
 discard up to 8 cards (4 in my case)
play each Tentaclid from discard pile

**Comment by SkyJedi** [comment] 2021-04-17 14:00
Dupe of #2428

**Closed by SkyJedi** 2021-04-17 14:00 UTC
