### ISSUE TITLE
Soul Snatcher does not work with tokens

### ISSUE THREAD

**Issue by siaka-kf** [keyteki/keyteki#3403] opened 2023-07-04 01:33 UTC
Expectation: I get amber when my token was destroyed and Soul Snatcher is in play.
Actual: Soul Snatcher didn't trigger.

Other "after a creature is destroyed" effects may not work either.

**Comment by romanogit** [comment] 2023-07-04 22:46
I believe this is the same root cause of https://github.com/keyteki/keyteki/issues/3384

The fix I did broke Mirror Shell, damn flip... 

Keep your eyes on #3398

**Comment by siaka-kf** [comment] 2023-08-08 00:53
#3398 was merged, but the problem is still there. Only tokens whose flipped cards were creatures were purged by Annihilation Ritual when instead all cards that were destroyed as tokens should be purged.

**Comment by strib** [comment] 2023-08-08 02:03
I believe it's been merged but is still being tested on the dev server and is not ready to go live on the real server yet.

**Closed** 2023-10-16 11:58 UTC
