### ISSUE TITLE
WOE: Non-token creature can use Trader Action

### ISSUE THREAD

**Issue by kensterel** [keyteki/keyteki#3371] opened 2023-06-25 14:18 UTC
This is the second time I've seen this. I didn't use the action this time since it would have messed up the game and killed Battlefield Evangelist + steal 1 amber. But you can see Battlefield Evangelist has an action prompt when it shouldn't. The last time I saw this was with Colonel Mariana (as a creature, not as a token), so I don't think it is anything specifically related to Battlefield Evangelist and creating tokens.

My best guess is you need Edict + One Stood Against Many to reproduce.

![image](https://github.com/keyteki/keyteki/assets/137358370/0c1010ed-5939-42a0-ba91-5a4f3cd8884f)

<details><summary>Click for match log </summary><blockquote>
Tuxedo brings Vis-de-Loup the Ostensibly Heroic to The Crucible
captain-gale brings Honourable “Staunch” Atwater to The Crucible
Tuxedo won the flip and is first player
 captain-gale has connected to the game server
 Tuxedo has connected to the game server
captain-gale
Heya, good luck
Tuxedo
hi glhf
Tuxedo is shuffling their deck
Tuxedo draws 6 card  s to their maximum of 6
captain-gale is shuffling their deck
captain-gale draws 6 card  s to their maximum of 6
Tuxedo draws 1 card 
Key phase - Tuxedo
Tuxedo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Tuxedo
Tuxedo chooses sanctum  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Battlefield Evangelist
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 1 card  to their maximum of 6
End of turn 1
Tuxedo: 0 Æmber  (0 keys) captain-gale: 0 Æmber  (0 keys)
TURN 1 - captain-gale
Key phase - captain-gale
captain-gale does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - captain-gale
captain-gale chooses untamed  as their active house this turn
Main phase - captain-gale
captain-gale plays Kangaphant
captain-gale plays Floomf
captain-gale plays Mollymawk
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 3 card  s to their maximum of 6
End of turn 1
Tuxedo: 0 Æmber  (0 keys) captain-gale: 0 Æmber  (0 keys)
TURN 2 - Tuxedo
Key phase - Tuxedo
Tuxedo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Tuxedo
Tuxedo chooses saurian  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Arm the Plebeians
Tuxedo gains an Æmber  due to Arm the Plebeians's bonus icon
Tuxedo gains an Æmber  due to Arm the Plebeians's bonus icon
Tuxedo uses Arm the Plebeians to make a token creature
Tuxedo plays Orator Hissaro
Tuxedo uses Orator Hissaro to ready and exalt its neighbors
Tuxedo uses Battlefield Evangelist to make Battlefield Evangelist fight Floomf
Tuxedo uses Battlefield Evangelist to make a token creature
Tuxedo plays Ankylo Formation
Tuxedo gains an Æmber  due to Ankylo Formation's bonus icon
Tuxedo chooses option ' Skirmish '
Tuxedo uses Ankylo Formation to apply a lasting effect to Battlefield Evangelist
Tuxedo plays Epic Poem
Tuxedo gains an Æmber  due to Epic Poem's bonus icon
Tuxedo uses Epic Poem to exalt Battlefield Evangelist and gain 2 Æmber 
Tuxedo uses Trader to reap with Trader
Tuxedo uses Trader to destroy Trader
Tuxedo uses Trader to remove its ward token
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 4 card  s to their maximum of 6
 Tuxedo declares Check!
End of turn 2
Tuxedo: 7 Æmber  (0 keys) captain-gale: 0 Æmber  (0 keys)
TURN 2 - captain-gale
Key phase - captain-gale
captain-gale does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - captain-gale
captain-gale chooses untamed  as their active house this turn
Main phase - captain-gale
captain-gale uses Kangaphant to reap with Kangaphant
captain-gale uses Kangaphant to destroy Kangaphant
captain-gale plays Infighting
captain-gale uses Infighting to make each creature deal damage to its right neighbor equal to its power
captain-gale plays Witch of the Dawn
captain-gale uses Witch of the Dawn to return Floomf to their hand
captain-gale plays Floomf
captain-gale uses Mollymawk to make Mollymawk fight Trader
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 2 card  s to their maximum of 6
End of turn 2
Tuxedo: 7 Æmber  (0 keys) captain-gale: 2 Æmber  (0 keys)
TURN 3 - Tuxedo
Key phase - Tuxedo
Tuxedo forges the yellow key  , paying 6 Æmber 
House phase - Tuxedo
Tuxedo chooses sanctum  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Colonel Mariana
Tuxedo gains an Æmber  due to Colonel Mariana's bonus icon
Tuxedo uses Colonel Mariana to capture 1 Æmber  from their opponent , placing it on Battlefield Evangelist and Colonel Mariana
Tuxedo plays Membership Drive
Tuxedo uses Membership Drive to make a token creature and gain 1 Æmber  for each friendly token creature
Tuxedo uses Battlefield Evangelist to make Battlefield Evangelist fight Floomf
Tuxedo uses Battlefield Evangelist to make a token creature
Tuxedo plays Taxing Journey
Tuxedo gains an Æmber  due to Taxing Journey's bonus icon
Tuxedo gains an Æmber  due to Taxing Journey's bonus icon
Tuxedo uses Taxing Journey
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 3 card  s to their maximum of 6
End of turn 3
Tuxedo: 5 Æmber  (1 key) captain-gale: 0 Æmber  (0 keys)
TURN 3 - captain-gale
Key phase - captain-gale
captain-gale does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - captain-gale
captain-gale chooses shadows  as their active house this turn
Main phase - captain-gale
captain-gale plays Scooped
captain-gale gains an Æmber  due to Scooped's bonus icon
captain-gale uses Scooped to deal 2 damage to Colonel Mariana
captain-gale uses Scooped to capture 1 Æmber  from Tuxedo on Colonel Mariana
captain-gale plays Brend the Fanatic
captain-gale uses Brend the Fanatic to cause Tuxedo to gain 1 Æmber 
captain-gale plays Hand Cannon attaching it to Mollymawk
captain-gale gains an Æmber  due to Hand Cannon's bonus icon
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 3 card  s to their maximum of 6
End of turn 3
Tuxedo: 5 Æmber  (1 key) captain-gale: 2 Æmber  (0 keys)
TURN 4 - Tuxedo
Key phase - Tuxedo
Tuxedo does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Tuxedo
Tuxedo chooses ekwidon  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Forced Retirement
Tuxedo uses Forced Retirement to destroy Mollymawk
Tuxedo uses Trader to reap with Trader
Tuxedo uses Trader to reap with Trader
Tuxedo plays Steward Su-Uzyanĕ
Tuxedo captures an Æmber  on Steward Su-Uzyanĕ due to Steward Su-Uzyanĕ's bonus icon
Tuxedo plays Dthoshră, Recruiter
Tuxedo plays Shrewd Investor
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 4 card  s to their maximum of 6
 Tuxedo declares Check!
End of turn 4
Tuxedo: 7 Æmber  (1 key) captain-gale: 2 Æmber  (0 keys)
TURN 4 - captain-gale
Key phase - captain-gale
captain-gale does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - captain-gale
captain-gale chooses unfathomable  as their active house this turn
Main phase - captain-gale
captain-gale changed tide  to High
captain-gale plays "Bubbles"
captain-gale uses "Bubbles" to return Battlefield Evangelist to the top of their owner's deck
captain-gale plays Abandon Ship
captain-gale gains an Æmber  due to Abandon Ship's bonus icon
captain-gale uses Abandon Ship to return "Bubbles", Shrewd Investor, Steward Su-Uzyanĕ, and Trader to their hand
captain-gale plays Seabringer Kekoa
captain-gale plays "Bubbles"
captain-gale uses "Bubbles" to return Dthoshră, Recruiter to the top of their owner's deck
captain-gale plays Frigorific Rod
captain-gale gains an Æmber  due to Frigorific Rod's bonus icon
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 3 card  s to their maximum of 6
captain-gale's chains are reduced by 1 to 2
 captain-gale declares Check!
End of turn 4
Tuxedo: 7 Æmber  (1 key) captain-gale: 8 Æmber  (0 keys)
TURN 5 - Tuxedo
Key phase - Tuxedo
Tuxedo forges the blue key  , paying 6 Æmber 
House phase - Tuxedo
Tuxedo chooses saurian  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Beware the Ides
Tuxedo gains an Æmber  due to Beware the Ides's bonus icon
Tuxedo plays Edict of Nerotaurus
Tuxedo gains an Æmber  due to Edict of Nerotaurus's bonus icon
Tuxedo gains an Æmber  due to Edict of Nerotaurus's bonus icon
Tuxedo plays Grammaticus Thrax
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
End of turn 5
Tuxedo: 4 Æmber  (2 keys) captain-gale: 8 Æmber  (0 keys)
TURN 5 - captain-gale
Key phase - captain-gale
captain-gale forges the blue key  , paying 6 Æmber 
House phase - captain-gale
captain-gale chooses untamed  as their active house this turn
Main phase - captain-gale
captain-gale plays Waste Not
captain-gale gains an Æmber  due to Waste Not's bonus icon
captain-gale uses Waste Not to destroy Brend the Fanatic and draw 2 cards 
captain-gale draws 2 card  s
captain-gale uses Brend the Fanatic to steal 3 Æmber  from Tuxedo
captain-gale plays Instrument of Silence attaching it to Witch of the Dawn
captain-gale plays Eldest Bear
captain-gale plays Mookling
captain-gale uses Witch of the Dawn to make Witch of the Dawn fight Trader
captain-gale uses Witch of the Dawn to gain 1 Æmber 
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 2 card  s to their maximum of 6
captain-gale's chains are reduced by 1 to 1
 captain-gale declares Check!
End of turn 5
Tuxedo: 1 Æmber  (2 keys) captain-gale: 7 Æmber  (1 key)
TURN 6 - Tuxedo
Key phase - Tuxedo
Tuxedo does not forge a key. They have 1 amber. The current cost is 8 Æmber 
House phase - Tuxedo
Tuxedo chooses sanctum  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Glorious Few
Tuxedo uses Glorious Few to gain 3 Æmber 
Tuxedo plays Battlefield Evangelist
Tuxedo gains an Æmber  due to Battlefield Evangelist's bonus icon
Tuxedo plays One Stood Against Many
Tuxedo gains an Æmber  due to One Stood Against Many's bonus icon
Tuxedo uses One Stood Against Many to make Battlefield Evangelist fight against 3 different creatures
Tuxedo uses Battlefield Evangelist to make Battlefield Evangelist fight Mookling
Tuxedo uses Battlefield Evangelist to make a token creature
Tuxedo plays Absolve
Tuxedo gains an Æmber  due to Absolve's bonus icon
Tuxedo uses Absolve to heal Colonel Mariana for 1 damage
Tuxedo uses Colonel Mariana to reap with Colonel Mariana
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 4 card  s to their maximum of 6
 Tuxedo declares Check!
End of turn 6
Tuxedo: 8 Æmber  (2 keys) captain-gale: 6 Æmber  (1 key)
TURN 6 - captain-gale
Key phase - captain-gale
captain-gale
That's a pretty cool nerotaurus and one stood against many interaction!
captain-gale forges the yellow key  , paying 6 Æmber 
House phase - captain-gale
Tuxedo
yeah, was super confused the first time that happened
captain-gale chooses shadows  as their active house this turn
Main phase - captain-gale
captain-gale plays Hornswoggle
captain-gale gains an Æmber  due to Hornswoggle's bonus icon
Tuxedo
but in most cases one attack and a reap is better anyway
captain-gale uses Hornswoggle to use Edict of Nerotaurus
captain-gale plays Loot or Pillage
captain-gale chooses option ' Capture 3 Æmber  '
captain-gale uses Loot or Pillage to capture 3 Æmber  from their opponent , placing it on "Bubbles"
Ready phase - captain-gale
captain-gale readies their cards 
Draw phase - captain-gale
captain-gale draws 2 card  s to their maximum of 6
captain-gale's chains are reduced by 1 to 0
End of turn 6
Tuxedo: 5 Æmber  (2 keys) captain-gale: 1 Æmber  (2 keys)
TURN 7 - Tuxedo
Key phase - Tuxedo
Tuxedo does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Tuxedo
Tuxedo
(although in this case I lost my reap due to it anyway)
Tuxedo chooses ekwidon  as their active house this turn
Main phase - Tuxedo
Tuxedo plays Ornate Talking Tray
Tuxedo gains an Æmber  due to Ornate Talking Tray's bonus icon
Tuxedo plays Steward Su-Uzyanĕ
Tuxedo captures an Æmber  on Grammaticus Thrax due to Steward Su-Uzyanĕ's bonus icon
Tuxedo plays Shrewd Investor
Tuxedo uses Trader to reap with Trader
Tuxedo discards Mass Buyout
Ready phase - Tuxedo
Tuxedo readies their cards 
Draw phase - Tuxedo
Tuxedo draws 4 card  s to their maximum of 6
 Tuxedo declares Check!
End of turn 7
Tuxedo: 7 Æmber  (2 keys) captain-gale: 0 Æmber  (2 keys)
TURN 7 - captain-gale
Key phase - captain-gale
captain-gale does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - captain-gale
captain-gale chooses unfathomable  as their active house this turn
Main phase - captain-gale
captain-gale plays Echo Pearl
captain-gale gains an Æmber  due to Echo Pearl's bonus icon
captain-gale plays Photic Raider
captain-gale uses Photic Raider to capture 2 Æmber  from their opponent , placing it on Photic Raider
captain-gale plays Abyssal Zealot
captain-gale uses Seabringer Kekoa to make Seabringer Kekoa fight Colonel Mariana
</blockquote></details>

**Comment by dmikalova** [comment] 2023-06-27 18:20
It looks like [this issue is back](https://github.com/keyteki/keyteki/issues/3241). I was able to reproduce this with strange shell today.

**Comment by dmikalova** [comment] 2023-06-28 05:33
Also related https://github.com/keyteki/keyteki/issues/3323

**Comment by MKHAUS** [comment] 2023-07-14 15:52
![KeyForge Omni](https://github.com/keyteki/keyteki/assets/13820050/367c3fe7-9b16-4c33-b37c-c53431e2402d)

Same issue for me - Flank creature is mistaken for a token creature.

**Comment by romanogit** [comment] 2023-08-20 00:47
Fixed by https://github.com/keyteki/keyteki/pull/3458

**Closed by romanogit** 2023-08-20 00:47 UTC
