### ISSUE TITLE
Replicator copies Reap effect of Tantadlin who has no Reap effect.

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#894] opened 2019-11-13 06:00 UTC
![what](https://user-images.githubusercontent.com/53681800/68737200-54964400-05a8-11ea-8be3-d879a5001c52.JPG)

Copied the fight effect, evidently.

**Comment by romanogit** [comment] 2019-11-13 16:30
Dupe of #862

**Closed by romanogit** 2019-11-13 16:30 UTC
