### ISSUE TITLE
Mavericks aren't always clear in hand

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2103] opened 2020-12-03 12:02 UTC
When you have several cards in hand and the first one is a maverick, it's hard to see that it's a maverick because the hand count covers the maverick house logo and the maverick symbol on the right-hand-side of the card is hidden by the other cards in your hand.

Could the hand count be moved either to the bottom or to the right, of cards in hand please?  Thank you.

![image](https://user-images.githubusercontent.com/55008319/101015237-00695380-355f-11eb-839f-28157e19ec2b.png)
![image](https://user-images.githubusercontent.com/55008319/101015245-04957100-355f-11eb-8ef9-cb4d53689a05.png)
![image](https://user-images.githubusercontent.com/55008319/101015260-0a8b5200-355f-11eb-8589-754eb4e3d8ee.png)

**Comment by romanogit** [comment] 2020-12-03 12:11
I believe this is a dupe of https://github.com/keyteki/keyteki/issues/577

**Comment by romanogit** [comment] 2020-12-03 12:42
Closing this one as a dupe

**Closed by romanogit** 2020-12-03 12:42 UTC
