### ISSUE TITLE
Please move "rematch" etc to another part of screen

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2276] opened 2021-02-24 12:18 UTC
it is enhancement, not an issue

this happens very frequently: when you clicking and working with your table, opponent concedes and you clicking accidentally rematch or rematch and swap decks. If opp is slow enough, you can write sorry missclick. if opp is fast enough, you have tough time explaining about missclick.

So please move these buttons :)

**Comment by SkyJedi** [comment] 2021-03-16 13:16
dupe of #2226

**Closed by SkyJedi** 2021-03-16 13:16 UTC
Labels: enhancement
