### ISSUE TITLE
Exterminate! Exterminate!

### ISSUE THREAD

**Issue by Jarimy123** [keyteki/keyteki#191] opened 2019-07-30 02:22 UTC
Not recognizing exhausted friendly Mars creatures only ready ones.  Cards says “For each Mars creature you control” ready or not.  Thanks.

**Comment by Achocholacek** [comment] 2019-07-30 03:40
Could not reproduce specific issue, card used exhausted mars cards no problem.

Wondering if maybe it's order of operations that tripped you up:

It is sequential, from left to right in your battle line, so you have to watch which enemy creatures you're destroying, if you accidentally "use" your 7 power Zorg to destroy a 1 Power Bad Penny, and the rest of the enemy board is 3+ power creatures and you only have 2 power Mindwarpers left, you can't do anything.

Can you confirm if this might have been the case, and if not, any other details about your board state you can remember?

**Comment by Jarimy123** [comment] 2019-07-30 10:54
I played out Xyixl Dominator so it was stunned and exhausted.  Had out Mindwarper and Shockworn both ready.  I played exterminate and it before I chose any creatures (he had 5 out, two 1 power, two 4 power, one 2 power) the 4 power ones were not selectable.   It is very possible I just didn’t track right, so I will see if it happens again - if it’s working for you odds are I am not recalling it right.  However, I was immediately wondering what was wrong and assumed it was from the exhausted/stunned guy.  Will see if it happens again with it.

**Comment by Jarimy123** [comment] 2019-07-30 12:42
![2019-07-30_084153](https://user-images.githubusercontent.com/46849213/62129937-e736ff80-b2a5-11e9-80be-cf21b158d4e1.jpg)

**Comment by Jarimy123** [comment] 2019-07-30 12:42
I got it to replicate - it's not registering Dominator as a Mars creature, at least when it is first played and comes in stunned/exhausted.

**Comment by Jarimy123** [comment] 2019-07-30 13:26
![2019-07-30_092554](https://user-images.githubusercontent.com/46849213/62132985-0d5f9e00-b2ac-11e9-8ff8-6e0893408064.jpg)

**Comment by Jarimy123** [comment] 2019-07-30 13:26
Doesn't care if Dominator isn't stunned or exhausted either

**Comment by Achocholacek** [comment] 2019-07-30 13:51
So I just recreated the exact scenario in your last screenshot (with dominator ready and unstunned), and also with dominator exhausted and stunned, and in both cases, it behaved as expected.

In your last screenshot, you have played Exterminate Exterminate, and it is parsing Mindwarper, and allowing you to destroy a non-mars creature with a power less than 2, which is only Bad Penny. My local copy behaved the same way.

As soon as you click on Bad Penny and destroy her, it then moves to parsing the Dominator, which should make either the Opponent's Niffle Ape or the Guardian Demon valid targets.

With EE! *not* being a "may" situation, were you possibly misinterpreting the game condition?

I'll definitely see if we can get some better messaging in place with how EE! is behaving so it's more obvious what's being triggered.

**Comment by Jarimy123** [comment] 2019-07-30 13:54
So the order it goes in is smallest to largest?

**Comment by Achocholacek** [comment] 2019-07-30 14:01
left to right across your battle line, so mindwarper first, then dominator. just so happens that's also smallest to largest, in this example.

**Comment by Jarimy123** [comment] 2019-07-30 14:16
Oh ok!  Yea that makes sense then.  Pretty sure every single instance I've had Dominator hasn't been on left because of taunt - I get it now.  Yea might help if maybe the system could show something for that to indicate it.  Not a huge deal, but I assume it might come up for others and they could start asking.  Thanks man!!

**Comment by Achocholacek** [comment] 2019-07-30 14:58
I'm going to close this ticket and re-open a new one for a feature enhancement. Thanks for your feedback!

**Closed by Achocholacek** 2019-07-30 14:58 UTC
