### ISSUE TITLE
Mars Needs Aember No Capture

### ISSUE THREAD

**Issue by avandever** [keyteki/keyteki#483] opened 2019-09-30 05:17 UTC
When I played Mars Needs Aember, my opponent had 7 aember, and two damaged non-Mars creatures (Champion Tabris and Succubus). I gained an aember for playing the card, but no aember was captured, leaving my opponent with 7. Upon review, they agreed that their creatures should've captured the aember. I'm including a screenshot as well as the log up until that point, and a link to the full game log on Crucible Tracker.
[Screencap](https://justpaste.it/5m57q)
[Paste](https://justpaste.it/5078v)
[Tracker](https://www.thecrucibletracker.com/games/ef4d6dd0-e33d-11e9-bfbf-491b7a2b9729/log)

**Comment by romanogit** [comment] 2020-12-03 16:10
Dupe of #411

**Closed by romanogit** 2020-12-03 16:10 UTC
Labels: bug
