### ISSUE TITLE
fangtooth cavern didn't destroy a creature at end of turn when 2 creatures were tied for lowest power

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#733] opened 2019-11-08 17:06 UTC
didn't think to take a screenshot so i'll describe the situation

My opponent played fangtooth cavern and ended their turn with a questor jarta with earthbind, and a bramble lynx and no other creatures in play on either side

no creature was destroyed at the end of that turn

at the end of their next turn, though, there was only one creature in play. a gatekeeper on my side. that time it worked

**Comment by sebastienode** [comment] 2019-11-08 17:39
The problem is more that the destruction is only on the opposite side.
Doesn’t matter the creature of the owner side.

**Comment by hydrophilic-attack** [comment] 2019-11-08 18:10
Aha ok

**Comment by Kaosumaru** [comment] 2019-11-08 21:01
I've tried to fix it, but I've not tested my patch yet #759

**Comment by SkyJedi** [comment] 2019-11-08 21:57
![image](https://user-images.githubusercontent.com/2967416/68513369-70b08300-0240-11ea-80ed-2094b1abe3cf.png)

**Comment by romanogit** [comment] 2019-11-09 05:51
Fixed by #759

**Closed by romanogit** 2019-11-09 05:51 UTC
