### ISSUE TITLE
Plunder flips cards over in hand.

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#3355] opened 2023-06-22 22:57 UTC
If a player uses plunder against an opponent, each card that is looked at will be facedown in the opponent's hand. They can play them if they call the correct house, but can't look at them. 

![Screenshot 2023-06-22 175648](https://github.com/keyteki/keyteki/assets/53681800/6e43ebc7-decd-460c-af52-ba1da4f19ce2)

**Comment by strib** [comment] 2023-06-22 23:04
Duplicate of #3316, possible fix is in review.

**Closed** 2023-06-27 19:23 UTC
Labels: duplicate, WoE
