### ISSUE TITLE
Deploy Mechanic

### ISSUE THREAD

**Issue by TheBrianFactor** [keyteki/keyteki#135] opened 2019-07-28 16:19 UTC
This error happened twice in the same match.

When attempting to Deploy Lamindra into my battleline I selected "Deploy Right" - with the impression that I'd select a creature and she would Deploy to the right of said creature.  I wanted to Deploy Lamindra in the center of my battleline.  Taking the steps above, I selected the creature, Yxilx Dominator, that I wanted to deploy to the right of.  After I selected the creature, Lamindra deployed TWO battleline spaces to the LEFT of Yxilx Dominator.  Ultimately being 3 spaces to the LEFT of where I wanted her.  Please correct - and thank you for all the hard work to get AoA live!

**Comment by issa** [comment] 2019-07-28 19:11
Possible duplicate of #95?

**Comment by cryogen** [comment] 2019-07-29 08:05
Copies the comment to #97 and closing this as a duplicate

**Closed by cryogen** 2019-07-29 08:05 UTC
Labels: duplicate
