### ISSUE TITLE
Exhuming Explo-Rover does not allow you to play him as upgrade

### ISSUE THREAD

**Issue by StVelten** [keyteki/keyteki#1077] opened 2020-01-03 15:30 UTC
As the title says: If you use Exhume:
("Choose a creature in your discard pile. **You may play that creature as if it belonged to the active house and was in your hand.**") 

to return Explo-Rover:
("Skirmish. Explo-rover may be played as an upgrade instead of a creature, with the text: “This creature gains skirmish.” )

you can only play him as creature and place him on your left or right flank.

Screenshot of a reproduced case (not the same as the log):
https://imgur.com/a/dKGtvY3

Log until: 
St-Velten is shuffling their deck
Orxel is shuffling their deck
St-Velten is playing as the Archon: Die kreischende „Axt“ Rose
Orxel is playing as the Archon: Das ungeschickte „Monster“ Attila
 Orxel has connected to the game server
 St-Velten has connected to the game server
St-Velten draws 6 cards  up to their maximum hand size of 6
Orxel draws 6 cards  up to their maximum hand size of 6
St-Velten
hey gl hf

Key phase - St-Velten
St-Velten does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses dis  as their active house this turn
Main phase - St-Velten
St-Velten plays Malison
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
End of turn 1
St-Velten: 0 Æmber  Orxel: 0 Æmber 

Turn 1
Key phase - Orxel
Orxel does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses logos  as their active house this turn
Main phase - Orxel
Orxel plays Memory Chip
Orxel plays Lateral Shift
Orxel uses Lateral Shift to play Flamewake Shaman
Orxel plays Flamewake Shaman
Orxel uses Flamewake Shaman to deal 2 damage to Malison
Orxel plays Dysania
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 3 cards  up to their maximum hand size of 6
End of turn 1
St-Velten: 0 Æmber  Orxel: 0 Æmber 

Turn 2
Key phase - St-Velten
St-Velten does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses dis  as their active house this turn
Main phase - St-Velten
St-Velten plays Library of the Damned
St-Velten plays The Evil Eye, gaining 1 Æmber 
St-Velten uses The Evil Eye to increase Orxel's key cost by 3 until the end of their next turn
St-Velten uses Malison to make Malison fight Dysania
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 3 cards  up to their maximum hand size of 6
End of turn 2
St-Velten: 1 Æmber  Orxel: 0 Æmber 

Turn 2
Key phase - Orxel
Orxel does not forge a key. They have 0 amber. The current cost is 9 Æmber 
House phase - Orxel
Orxel chooses logos  as their active house this turn
Orxel uses Memory Chip to archive a card 
Main phase - Orxel
Orxel plays Cutthroat Research, gaining 1 Æmber 
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 2 cards  up to their maximum hand size of 6
End of turn 2
St-Velten: 1 Æmber  Orxel: 1 Æmber 

Turn 3
Key phase - St-Velten
St-Velten does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses staralliance  as their active house this turn
Main phase - St-Velten
St-Velten discards United Action
St-Velten plays Armsmaster Molina
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 2 cards  up to their maximum hand size of 6
End of turn 3
St-Velten: 1 Æmber  Orxel: 1 Æmber 

Turn 3
Key phase - Orxel
Orxel does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses logos  as their active house this turn
Orxel uses Memory Chip to archive a card 
Main phase - Orxel
Orxel plays Titan Guardian
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 2 cards  up to their maximum hand size of 6
End of turn 3
St-Velten: 1 Æmber  Orxel: 1 Æmber 

Turn 4
Key phase - St-Velten
St-Velten does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses brobnar  as their active house this turn
Main phase - St-Velten
St-Velten plays Barn Razing
St-Velten uses Barn Razing to cause their opponent to lose 1 Æmber  each time a friendly creature fights
St-Velten plays Narp
St-Velten plays Ganger Chieftain
St-Velten uses Ganger Chieftain to ready and fight with a neighboring creature
St-Velten uses Narp to make Narp fight Titan Guardian
loses 1 Æmber  due to Barn Razing's effect
St-Velten discards Ballcano
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 4 cards  up to their maximum hand size of 6
End of turn 4
St-Velten: 1 Æmber  Orxel: 0 Æmber 

Turn 4
Key phase - Orxel
Orxel does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses staralliance  as their active house this turn
Main phase - Orxel
Orxel plays Commander Chan
Orxel plays Chief Engineer Walls
Orxel plays Universal Translator, gaining 1 Æmber  attaching it to Chief Engineer Walls
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 3 cards  up to their maximum hand size of 6
End of turn 4
St-Velten: 1 Æmber  Orxel: 1 Æmber 

Turn 5
Key phase - St-Velten
St-Velten does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses brobnar  as their active house this turn
Main phase - St-Velten
St-Velten plays Cybergiant Rig, gaining 1 Æmber  attaching it to Narp
St-Velten uses Cybergiant Rig to heal Narp fully
St-Velten plays The Flex
St-Velten uses The Flex to exhaust Narp and gain 6 Æmber 
St-Velten uses Ganger Chieftain to make Ganger Chieftain fight Chief Engineer Walls
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 2 cards  up to their maximum hand size of 6
St-Velten uses Cybergiant Rig to remove 1 power counter from Narp
 St-Velten declares Check!
End of turn 5
St-Velten: 8 Æmber  Orxel: 1 Æmber 

Turn 5
Key phase - Orxel
Orxel does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses staralliance  as their active house this turn
Main phase - Orxel
Orxel plays Xenotraining, gaining 1 Æmber 
Orxel uses Xenotraining to capture 1 Æmber  on a friendly creature for each house represented by friendly creatures
Orxel plays Light of the Archons, gaining 1 Æmber  attaching it to Chief Engineer Walls
Orxel uses Chief Engineer Walls to reap with Chief Engineer Walls
Orxel uses Chief Engineer Walls to use Flamewake Shaman
Orxel uses Flamewake Shaman to make Flamewake Shaman fight Armsmaster Molina
St-Velten uses Armsmaster Molina to deal 3 damage to Flamewake Shaman
Orxel uses Commander Chan to reap with Commander Chan
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 2 cards  up to their maximum hand size of 6
End of turn 5
St-Velten: 6 Æmber  Orxel: 5 Æmber 

Turn 6
Key phase - St-Velten
St-Velten forges the red key  , paying 6 Æmber 
House phase - St-Velten
St-Velten chooses staralliance  as their active house this turn
Main phase - St-Velten
St-Velten plays Stealth Mode, gaining 1 Æmber 
St-Velten uses Stealth Mode to stop Orxel from playing any actions on their next turn
St-Velten plays Explo-rover, attaching it to Narp
St-Velten plays Cloaking Dongle, gaining 1 Æmber  attaching it to Narp
St-Velten plays Zap, gaining 1 Æmber 
St-Velten uses Zap to deal 1 damage to a creature for each house represented among creatures in play
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 4 cards  up to their maximum hand size of 6
St-Velten uses Cybergiant Rig to remove 1 power counter from Narp
End of turn 6
St-Velten: 3 Æmber  Orxel: 5 Æmber 

Turn 6
Key phase - Orxel
Orxel does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses logos  as their active house this turn
Orxel uses Memory Chip to archive a card 
Main phase - Orxel
Orxel plays Memory Chip
Orxel plays Crazy Killing Machine
Orxel plays Groupthink Tank
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 4 cards  up to their maximum hand size of 6
End of turn 6
St-Velten: 3 Æmber  Orxel: 5 Æmber 

Turn 7
Key phase - St-Velten
St-Velten does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses brobnar  as their active house this turn
Main phase - St-Velten
St-Velten plays Mogghunter
St-Velten uses Ganger Chieftain to make Ganger Chieftain fight Chief Engineer Walls
St-Velten uses Narp to make Narp fight Chief Engineer Walls
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 1 cards  up to their maximum hand size of 6
St-Velten uses Cybergiant Rig to remove 1 power counter from Narp
End of turn 7
St-Velten: 5 Æmber  Orxel: 5 Æmber 

Turn 7
Key phase - Orxel
Orxel does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Orxel
Orxel chooses logos  as their active house this turn
Orxel uses Memory Chip to archive a card 
Orxel uses Memory Chip to archive a card 
Main phase - Orxel
Orxel plays Memory Chip
Orxel uses Crazy Killing Machine to discard the top card  of each player's deck: Gron Nine-Toes and Rhetor Gallim
Orxel chooses to destroy Narp with Crazy Killing Machine
Crazy Killing Machine is destroyed by its ability
Orxel uses Groupthink Tank to reap with Groupthink Tank
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 3 cards  up to their maximum hand size of 6
 Orxel declares Check!
End of turn 7
St-Velten: 5 Æmber  Orxel: 6 Æmber 

Turn 8
Key phase - St-Velten
St-Velten does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - St-Velten
St-Velten chooses dis  as their active house this turn
Main phase - St-Velten
St-Velten uses Library of the Damned to archive a card 
St-Velten plays The Evil Eye, gaining 1 Æmber 
St-Velten uses The Evil Eye to increase Orxel's key cost by 3 until the end of their next turn
St-Velten plays Exhume, gaining 1 Æmber 
St-Velten uses Exhume to play Malison
St-Velten plays Malison
St-Velten plays Festering Touch, gaining 1 Æmber 
St-Velten uses Festering Touch to deal 3 damage to Commander Chan
St-Velten plays Buzzle
Ready phase - St-Velten
St-Velten readies all of their cards 
Draw phase - St-Velten
St-Velten draws 5 cards  up to their maximum hand size of 6
 St-Velten declares Check!
End of turn 8
St-Velten: 8 Æmber  Orxel: 6 Æmber 

Turn 8
Key phase - Orxel
Orxel does not forge a key. They have 6 amber. The current cost is 9 Æmber 
House phase - Orxel
Orxel chooses staralliance  as their active house this turn
Main phase - Orxel
Orxel plays Red Alert
Orxel uses Red Alert to deal 3 damage to Mogghunter, Ganger Chieftain, Malison, and Buzzle
Orxel plays Commander Chan
Orxel plays CXO Taber
Ready phase - Orxel
Orxel readies all of their cards 
Draw phase - Orxel
Orxel draws 3 cards  up to their maximum hand size of 6
End of turn 8
St-Velten: 8 Æmber  Orxel: 6 Æmber 

Turn 9
Key phase - St-Velten
St-Velten forges the blue key  , paying 6 Æmber 
House phase - St-Velten
St-Velten chooses dis  as their active house this turn
Main phase - St-Velten
St-Velten uses Library of the Damned to archive a card 
St-Velten plays Exhume, gaining 1 Æmber 
St-Velten uses Exhume to play Explo-rover
St-Velten plays Explo-rover

**Comment by romanogit** [comment] 2020-01-03 16:27
Dupe of #938

**Comment by StVelten** [comment] 2020-01-03 17:12
sorry

**Comment by romanogit** [comment] 2020-01-03 18:11
Not a problem. This one is tricky to solve.

**Comment by romanogit** [comment] 2020-05-11 04:06
I am reopening this one for discussion. Are you saying `Exhume` should allow playing Explo-Rover as upgrade? Or only as creature?

**Comment by romanogit** [comment] 2020-07-08 13:23
According to latest Crucible Cast:
https://archonarcana.com/Crucible_Cast#Episode_21
![image](https://user-images.githubusercontent.com/2104075/86923504-83979200-c104-11ea-8141-5c133b559517.png)

It is working as expected, but there is still one failing scenario. I will open a separate ticket for that, which is a bit more complex.

**Closed by romanogit** 2020-07-08 13:23 UTC
