### ISSUE TITLE
pandemonium

### ISSUE THREAD

**Issue by naife95** [keyteki/keyteki#520] opened 2019-10-05 09:27 UTC
i have a deck with 3 pandemoniums, and i use it a lot.
lot of times when i play it is bugged, and just 1 of (for example) 8 creatures capture the aember (and the creatures was all undamaged).

**Comment by jeremylarner** [comment] 2019-10-05 11:30
I'm happy to try and fix this, but every time I try it out, it works perfectly. 

If you could give me a game state (cards on the board, etc) where it consistently bugs, that would be super helpful

**Comment by bensissel** [comment] 2019-10-07 03:22
From what I've seen, it's when there are more than 10 total creatures between the two players, but i'm not sure if that's the cause.

**Comment by Achocholacek** [comment] 2019-10-25 13:35
externally reported:
"Played a Pandemonium. I was at 14 Amber, OP was at 4 Amber. They had 4 undamaged creatures, I had 7+. I was prompted to place opponent's amber on my dudes and then that was it. Opponent's 4 legal undamaged creatures did not capture"

So it may very well be related to large number of creatures.

**Comment by romanogit** [comment] 2020-12-03 16:16
Fixed by Capture refactor..

Before:
![image](https://user-images.githubusercontent.com/2104075/101056404-b46fdc00-3569-11eb-9070-f3f6a98a0d34.png)

After:

![image](https://user-images.githubusercontent.com/2104075/101056449-bfc30780-3569-11eb-9acc-ad22c75d022c.png)

**Closed by romanogit** 2020-12-03 16:16 UTC
Labels: unable to reproduce
