### ISSUE TITLE
Opponent used my The Golden Spiral to reap with my creature

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2262] opened 2021-02-09 12:43 UTC
My opponent used "Remote Access" to use my "The Golden Spiral" to reap with my "C.A.N.D.L.E. Unit" and they gained an aember by doing so.

![image](https://user-images.githubusercontent.com/55008319/107365072-333a4580-6ad4-11eb-92a4-65fd350ac0e9.png)

**Comment by romanogit** [comment] 2021-02-09 14:05
I think there is a relevant fact here that they did not have any creatures in play.

**Comment by romanogit** [comment] 2021-02-23 18:59
I am unable to reproduce this issue. Still not sure what can cause it.

**Comment by romanogit** [comment] 2021-06-30 13:56
Dupe of https://github.com/keyteki/keyteki/issues/1579

**Closed by romanogit** 2021-06-30 13:56 UTC
Labels: unable to reproduce
