### ISSUE TITLE
Haedroth's Wall increases power on creatures not on a flank. 

### ISSUE THREAD

**Issue by thechillturtle** [keyteki/keyteki#2221] opened 2021-01-21 22:35 UTC
Opponent's Fila the Researcher received +2 power seemingly from Wall despite not being on a flank.

![Fila](https://user-images.githubusercontent.com/75549336/105420769-eff46180-5c0e-11eb-86ac-c88d739a450a.png)

achillturtle won the flip and is first player
 popman has connected to the game server
 achillturtle has connected to the game server
achillturtle
hey, gl!
achillturtle is shuffling their deck
achillturtle draws 6 card  s to their maximum of 6
popman is shuffling their deck
popman draws 6 card  s to their maximum of 6
achillturtle draws 1 card 
popman
hi hf
Key phase - achillturtle
achillturtle does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses logos  as their active house this turn
Main phase - achillturtle
achillturtle plays Library of Babble
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
End of turn 1
achillturtle: 0 Æmber  (0 keys) popman: 0 Æmber  (0 keys)
TURN 1 - popman
Key phase - popman
popman does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses mars  as their active house this turn
Main phase - popman
popman plays Mindwarper
popman plays Vezyma Thinkdrone
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 2 card  s to their maximum of 6
End of turn 1
achillturtle: 0 Æmber  (0 keys) popman: 0 Æmber  (0 keys)
TURN 2 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses logos  as their active house this turn
Main phase - achillturtle
achillturtle uses Library of Babble to draw 1 card 
achillturtle draws 1 card 
achillturtle plays Foggify
achillturtle gains an Æmber  due to Foggify's bonus icon
achillturtle uses Foggify to stop popman from fighting next turn
achillturtle plays Batdrone
achillturtle plays Dextre
achillturtle plays Research Smoko
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 3 card  s to their maximum of 6
End of turn 2
achillturtle: 1 Æmber  (0 keys) popman: 0 Æmber  (0 keys)
TURN 2 - popman
Key phase - popman
popman does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses mars  as their active house this turn
Main phase - popman
popman uses Mindwarper to capture 1 Æmber  from achillturtle, placing it on Batdrone
popman uses Vezyma Thinkdrone to reap with Vezyma Thinkdrone
popman plays Mothergun
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 1 card  to their maximum of 6
End of turn 2
achillturtle: 0 Æmber  (0 keys) popman: 1 Æmber  (0 keys)
TURN 3 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses shadows  as their active house this turn
Main phase - achillturtle
achillturtle plays Nerve Blast
achillturtle uses Nerve Blast to steal 1 Æmber  from popman
achillturtle uses Nerve Blast to deal 2 damage to Mindwarper
achillturtle plays Shadow Self
achillturtle plays Dodger
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 3 card  s to their maximum of 6
End of turn 3
achillturtle: 1 Æmber  (0 keys) popman: 0 Æmber  (0 keys)
TURN 3 - popman
Key phase - popman
popman does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses sanctum  as their active house this turn
Main phase - popman
popman plays The Spirit’s Way
popman uses The Spirit’s Way to destroy Dodger, Shadow Self, Dextre, and Vezyma Thinkdrone
achillturtle uses Dextre to return Dextre to the top of their deck
popman plays Abond the Armorsmith
popman plays Maruck the Marked
popman plays Martyr’s End
popman gains an Æmber  due to Martyr’s End's bonus icon
popman uses Martyr’s End to destroy any number of friendly creatures. gain 1 Æmber  for each creature destroyed this way.
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 4 card  s to their maximum of 6
End of turn 3
achillturtle: 1 Æmber  (0 keys) popman: 3 Æmber  (0 keys)
TURN 4 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses mars  as their active house this turn
Main phase - achillturtle
achillturtle plays Soft Landing
achillturtle uses Soft Landing to make the next creature/artifact played this turn enter play ready
achillturtle plays Zorg
achillturtle uses Soft Landing to ready Zorg
achillturtle exhausts Zorg to remove its stun
achillturtle plays Zyzzix the Many
achillturtle plays Biomatrix Backup attaching it to Zorg
achillturtle gains an Æmber  due to Biomatrix Backup's bonus icon
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 4 card  s to their maximum of 6
End of turn 4
achillturtle: 2 Æmber  (0 keys) popman: 3 Æmber  (0 keys)
TURN 4 - popman
Key phase - popman
popman does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses logos  as their active house this turn
Main phase - popman
popman plays Director of Z.Y.X.
popman plays Z.Y.X. Researcher
popman uses Z.Y.X. Researcher to archive Martyr’s End
popman plays Labwork
popman gains an Æmber  due to Labwork's bonus icon
popman uses Labwork to archive a card 
popman plays Sloppy Labwork
popman gains an Æmber  due to Sloppy Labwork's bonus icon
popman uses Sloppy Labwork to archive a card 
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 6 card  s to their maximum of 6
End of turn 4
achillturtle: 2 Æmber  (0 keys) popman: 5 Æmber  (0 keys)
TURN 5 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses logos  as their active house this turn
Main phase - achillturtle
achillturtle uses Library of Babble to draw 1 card 
achillturtle draws 1 card 
achillturtle plays Dextre
achillturtle uses Dextre to capture 1 Æmber  from their opponent , placing it on Dextre
achillturtle plays Foggify
achillturtle gains an Æmber  due to Foggify's bonus icon
achillturtle uses Foggify to stop popman from fighting next turn
achillturtle plays Phase Shift
achillturtle uses Phase Shift to allow them to play one non-Logos card  this turn
achillturtle uses Batdrone to make Batdrone fight Director of Z.Y.X.
achillturtle uses Batdrone to steal 1 Æmber  from popman
achillturtle uses Research Smoko to make Research Smoko fight Director of Z.Y.X.
achillturtle uses Research Smoko to archive the top card  of their deck
achillturtle plays Relentless Whispers
achillturtle gains an Æmber  due to Relentless Whispers's bonus icon
achillturtle uses Relentless Whispers to deal 2 damage to Director of Z.Y.X.
achillturtle uses Relentless Whispers to steal 1 Æmber  from popman
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 3 card  s to their maximum of 6
 achillturtle declares Check!
End of turn 5
achillturtle: 6 Æmber  (0 keys) popman: 2 Æmber  (0 keys)
TURN 5 - popman
Key phase - popman
popman does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses mars  as their active house this turn
popman moves all the cards  in their archives to their hand
Main phase - popman
popman uses Mothergun to reveal Glyxl Proliferator, Mindwarper, and Nyzyk Resonator from their hand, and deal 3 damage to Batdrone
popman plays Nyzyk Resonator
popman plays Glyxl Proliferator
popman plays Mindwarper
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
End of turn 5
achillturtle: 6 Æmber  (0 keys) popman: 3 Æmber  (0 keys)
TURN 6 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 6 amber. The current cost is 10 Æmber 
House phase - achillturtle
achillturtle chooses mars  as their active house this turn
Main phase - achillturtle
achillturtle plays Yxili Marauder
achillturtle uses Yxili Marauder to capture 2 Æmber  from their opponent , placing it on Yxili Marauder
achillturtle plays Mindwarper
achillturtle plays Vezyma Thinkdrone
achillturtle uses Zyzzix the Many to make Zyzzix the Many fight Z.Y.X. Researcher
achillturtle uses Zyzzix the Many to reveal Ganymede Archivist
achillturtle uses Zorg to make Zorg fight Nyzyk Resonator
achillturtle uses Zorg to stun Glyxl Proliferator, Mindwarper, and Nyzyk Resonator
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 4 card  s to their maximum of 6
 achillturtle declares Check!
End of turn 6
achillturtle: 6 Æmber  (0 keys) popman: 1 Æmber  (0 keys)
TURN 6 - popman
Key phase - popman
popman does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses logos  as their active house this turn
Main phase - popman
popman plays Helper Bot
popman uses Helper Bot to allow them to play one non-Logos card  this turn
popman plays Mighty Lance
popman uses Mighty Lance to deal 3 damage to Mindwarper and Vezyma Thinkdrone
popman plays Master the Theory
popman gains an Æmber  due to Master the Theory's bonus icon
popman plays Professor Sutterkin
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 4 card  s to their maximum of 6
End of turn 6
achillturtle: 6 Æmber  (0 keys) popman: 2 Æmber  (0 keys)
TURN 7 - achillturtle
Key phase - achillturtle
achillturtle forges the red key  , paying 6 Æmber 
House phase - achillturtle
achillturtle chooses mars  as their active house this turn
Main phase - achillturtle
achillturtle uses Yxili Marauder to make Yxili Marauder fight Mindwarper
achillturtle uses Zorg to make Zorg fight Mindwarper
achillturtle uses Zorg to stun Glyxl Proliferator, Professor Sutterkin, and Mindwarper
achillturtle uses Zyzzix the Many to make Zyzzix the Many fight Helper Bot
achillturtle uses Zyzzix the Many to reveal Umbra
achillturtle plays Phylyx the Disintegrator
achillturtle plays Ulyq Megamouth
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 3 card  s to their maximum of 6
End of turn 7
achillturtle: 0 Æmber  (1 key) popman: 2 Æmber  (0 keys)
TURN 7 - popman
Key phase - popman
popman does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses mars  as their active house this turn
Main phase - popman
popman uses Mothergun to reveal Agent Hoo-man and Xanthyx Harvester from their hand, and deal 2 damage to Phylyx the Disintegrator
popman exhausts Glyxl Proliferator to remove its stun
popman plays Agent Hoo-man
popman plays Xanthyx Harvester
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 2 card  s to their maximum of 6
End of turn 7
achillturtle: 0 Æmber  (1 key) popman: 2 Æmber  (0 keys)
TURN 8 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses shadows  as their active house this turn
Main phase - achillturtle
achillturtle plays Booby Trap
achillturtle gains an Æmber  due to Booby Trap's bonus icon
achillturtle uses Booby Trap to deal 4 damage to Agent Hoo-man and 2 to their neighbors
achillturtle plays Oubliette
achillturtle uses Oubliette to purge Glyxl Proliferator
achillturtle plays Poison Wave
achillturtle gains an Æmber  due to Poison Wave's bonus icon
achillturtle uses Poison Wave to deal 2 damage to all creatures
achillturtle plays Noddy the Thief
achillturtle plays Hidden Stash
achillturtle gains an Æmber  due to Hidden Stash's bonus icon
achillturtle uses Hidden Stash to archive a card 
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 6 card  s to their maximum of 6
End of turn 8
achillturtle: 3 Æmber  (1 key) popman: 2 Æmber  (0 keys)
TURN 8 - popman
Key phase - popman
popman does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses sanctum  as their active house this turn
Main phase - popman
popman plays Haedroth’s Wall
popman plays Challe the Safeguard
popman plays Protect the Weak attaching it to Challe the Safeguard
popman gains an Æmber  due to Protect the Weak's bonus icon
popman plays Seraphic Armor attaching it to Challe the Safeguard
popman gains an Æmber  due to Seraphic Armor's bonus icon
popman uses Seraphic Armor to heal Challe the Safeguard fully
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 4 card  s to their maximum of 6
End of turn 8
achillturtle: 3 Æmber  (1 key) popman: 4 Æmber  (0 keys)
TURN 9 - achillturtle
Key phase - achillturtle
achillturtle does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - achillturtle
achillturtle chooses mars  as their active house this turn
Main phase - achillturtle
achillturtle plays Mothergun
achillturtle plays Yxili Marauder
achillturtle uses Yxili Marauder to capture 4 Æmber  from their opponent , placing it on Yxili Marauder
achillturtle uses Ulyq Megamouth to reap with Ulyq Megamouth
achillturtle uses Ulyq Megamouth to use Noddy the Thief
achillturtle uses Noddy the Thief to reap with Noddy the Thief
achillturtle uses Zyzzix the Many to reap with Zyzzix the Many
achillturtle uses Zyzzix the Many to reveal Urchin
achillturtle uses Yxili Marauder to reap with Yxili Marauder
achillturtle uses Zorg to reap with Zorg
Ready phase - achillturtle
achillturtle readies all of their cards 
Draw phase - achillturtle
achillturtle draws 3 card  s to their maximum of 6
achillturtle's deck has run out of cards, so they shuffle
 achillturtle declares Check!
End of turn 9
achillturtle: 8 Æmber  (1 key) popman: 0 Æmber  (0 keys)
TURN 9 - popman
Key phase - popman
popman does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - popman
popman chooses logos  as their active house this turn
Main phase - popman
popman plays Professor Sutterkin
popman plays Fila the Researcher
popman plays Archimedes
popman uses Fila the Researcher to draw 1 card 
popman draws 1 card 
popman plays Labwork
popman gains an Æmber  due to Labwork's bonus icon
popman uses Labwork to archive a card 
Ready phase - popman
popman readies all of their cards 
Draw phase - popman
popman draws 4 card  s to their maximum of 6
End of turn 9
achillturtle: 8 Æmber  (1 key) popman: 1 Æmber  (0 keys)
TURN 10 - achillturtle
Key phase - achillturtle
 popman concedes
 achillturtle has won the game
popman
gg
 popman has left the game
achillturtle
gg

**Comment by romanogit** [comment] 2021-04-30 14:17
Need to investigate if it is just a client side issue (rendering the power)

**Comment by romanogit** [comment] 2021-06-28 22:45
Closing as unable to reproduce... Please, reopen if it happens again. It seems to be an old rendering issue.

**Closed by romanogit** 2021-06-28 22:45 UTC
Labels: unable to reproduce
