### ISSUE TITLE
RedHawck was unnable to use his action abillity vs Aemberskies decks

### ISSUE THREAD

**Issue by pedrogodoy159** [keyteki/keyteki#4358] opened 2024-10-22 10:36 UTC
Hi, so I played 2 games yesterday with this deck:

https://decksofkeyforge.com/decks/dd547e3b-2272-4440-8c44-1c89bf72291d

both games where against aemberskies deck, and with closed view of the oponnents cards.

When I played Redhawk, I could reap and fight, but never was I able to use his action, that gives 1 aember to both players and generates a token for me.

Today I replicated the issue, as is in the picture, but by trying, I saw that agains a Grimm Remminder's deck, the ability, appeared normaly. I tried to play redhawk with or without creatures in play, and in both cases his action button is not available, but only when I played vs Aemberskies deck.

![AS with creature](https://github.com/user-attachments/assets/4bc4cb0c-b26d-4b67-b67f-a6b47adb1d0d)
Log of the game

pedrogodoy159 won the flip and is first player
 KammyBlack has connected to the game server
 pedrogodoy159 has connected to the game server
pedrogodoy159 is shuffling their deck
pedrogodoy159 draws 6 card s to their maximum of 6
KammyBlack is shuffling their deck
KammyBlack draws 6 card s to their maximum of 6
pedrogodoy159 draws 1 card
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses redemption as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 discards Bordan the Redeemed
Ready phase - pedrogodoy159
Draw phase - pedrogodoy159
pedrogodoy159 draws 1 card to their maximum of 6
End of turn 1
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 1 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses geistoid as their active house this turn
Main phase - KammyBlack
Ready phase - KammyBlack
Draw phase - KammyBlack
KammyBlack draws 1 card to their maximum of 6
End of turn 1
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 2 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses skyborn as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 discards Rose of Sharon
pedrogodoy159 discards Skulking Saboteurs
pedrogodoy159 discards Prop Dusting
Ready phase - pedrogodoy159
Draw phase - pedrogodoy159
pedrogodoy159 draws 3 card s to their maximum of 6
End of turn 2
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 2 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses geistoid as their active house this turn
Main phase - KammyBlack
Ready phase - KammyBlack
Draw phase - KammyBlack
End of turn 2
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 3 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses untamed as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 discards Niffle Sanctuary
pedrogodoy159 discards Fogbank
pedrogodoy159 discards Niffle Ape
Ready phase - pedrogodoy159
Draw phase - pedrogodoy159
pedrogodoy159 draws 3 card s to their maximum of 6
End of turn 3
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 3 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses geistoid as their active house this turn
Main phase - KammyBlack
Ready phase - KammyBlack
Draw phase - KammyBlack
End of turn 3
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 4 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses redemption as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 discards Steadfast Commitment
pedrogodoy159 discards Grey Abbess
pedrogodoy159 discards Even Ivan
Ready phase - pedrogodoy159
Draw phase - pedrogodoy159
pedrogodoy159 draws 3 card s to their maximum of 6
End of turn 4
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 4 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses dis as their active house this turn
Main phase - KammyBlack
KammyBlack plays Dust Imp
Ready phase - KammyBlack
KammyBlack readies their cards
Draw phase - KammyBlack
KammyBlack draws 1 card to their maximum of 6
End of turn 4
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 5 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses skyborn as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 plays Redhawk
Ready phase - pedrogodoy159
pedrogodoy159 readies their cards
Draw phase - pedrogodoy159
pedrogodoy159 draws 1 card to their maximum of 6
End of turn 5
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 5 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses geistoid as their active house this turn
Main phase - KammyBlack
Ready phase - KammyBlack
KammyBlack readies their cards
Draw phase - KammyBlack
End of turn 5
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 6 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses skyborn as their active house this turn
Main phase - pedrogodoy159

![AS with no creature](https://github.com/user-attachments/assets/85e7cc01-c9b0-44eb-af78-70dc101c20b1)

Log of the second game:
 pedrogodoy159 won the flip and is first player
 KammyBlack has connected to the game server
 pedrogodoy159 has connected to the game server
pedrogodoy159 is shuffling their deck
pedrogodoy159 draws 6 card s to their maximum of 6
KammyBlack is shuffling their deck
KammyBlack draws 6 card s to their maximum of 6
pedrogodoy159 draws 1 card
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses skyborn as their active house this turn
Main phase - pedrogodoy159
pedrogodoy159 plays Redhawk
Ready phase - pedrogodoy159
pedrogodoy159 readies their cards
Draw phase - pedrogodoy159
End of turn 1
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 1 - KammyBlack
Key phase - KammyBlack
KammyBlack does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - KammyBlack
KammyBlack chooses geistoid as their active house this turn
Main phase - KammyBlack
Ready phase - KammyBlack
Draw phase - KammyBlack
KammyBlack draws 1 card to their maximum of 6
End of turn 1
pedrogodoy159: 0 Æmber (0 keys) KammyBlack: 0 Æmber (0 keys)
Turn 2 - pedrogodoy159
Key phase - pedrogodoy159
pedrogodoy159 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - pedrogodoy159
pedrogodoy159 chooses skyborn as their active house this turn
Main phase - pedrogodoy159

**Comment by pedrogodoy159** [comment] 2024-10-22 10:42
Here, with the ability showing and working normally, against a GR deck

![against GR deck](https://github.com/user-attachments/assets/2a44789d-52d4-44c1-a669-efbe2734f635)

**Comment by strib** [comment] 2024-10-22 14:25
Duplicate of #4346 (which is fixed as of today).

**Closed by strib** 2024-10-22 14:25 UTC
