### ISSUE TITLE
Was able to bypass Aember capture by Sir Marrows when reaping with The Grey Rider

### ISSUE THREAD

**Issue by Twizzlebutt** [keyteki/keyteki#257] opened 2019-08-02 17:41 UTC
My opponent had out 2 Sir Marrows.  I had out 2 The Grey Rider's.  I reaped with one The Grey Rider and was prompted to respond, I clicked done as I didn't want to use The Grey Rider's reap ability and I was granted one aember to my pool and Sir Marrows didn't capture it.  I did see that his 2 Sir Marrows were highlighted so I could pick which one captured the aember, but I was able to click done and avoid that.  It happened with the 2nd The Grey Rider I reaped with as well.  

The attached screenshot shows the board state after I fixed the Aember issue manually and then played one more card.

![Board_State](https://user-images.githubusercontent.com/49589454/62388366-bfa09b00-b522-11e9-9b74-08f6b05ffa3b.png)

**Comment by romanogit** [comment] 2019-09-11 01:00
I tried to recreate this by adding 3 Sir Marrows and it looks like that reaping caused each Sir Marrows to capture an amber:

![image](https://user-images.githubusercontent.com/2104075/64660360-5a3fa400-d416-11e9-838f-bd9e5ffefe90.png)

**Comment by romanogit** [comment] 2020-12-02 23:09
It might have the same root cause as #859

**Comment by romanogit** [comment] 2020-12-03 16:07
Fixed by Timing and Prompt Refactor :
![image](https://user-images.githubusercontent.com/2104075/101055176-76be8380-3568-11eb-9ab1-f12912b19748.png)

**Closed by romanogit** 2020-12-03 16:07 UTC
Labels: Timing Refactor
