### ISSUE TITLE
Murkens and Mimicry

### ISSUE THREAD

**Issue by charzendat** [keyteki/keyteki#667] opened 2019-10-31 15:30 UTC
I played Murkens (shadow creature) which allows me to play the top card of my opponent's deck as if it were mine. The card that got played was Mimicry (untamed action) which allows me to copy any action card in my opponent's discard pile. However the game offered up my discard pile to choose a card to copy from, not my opponents. I was able to choose a card to copy but I should have been given my opponent's discard pile.

**Comment by romanogit** [comment] 2019-11-05 20:19
Reopened as it was closed by an incorrect commit message. Sorry.

**Comment by fakatwork** [comment] 2020-10-11 11:22
bug reconfirmed by another user a couple of days ago

**Comment by romanogit** [comment] 2020-12-02 23:15
Dupe of #2070 - closing this one

**Closed by romanogit** 2020-12-02 23:15 UTC
