### ISSUE TITLE
I found a bug on TCO (Dark Aember Vault) 

### ISSUE THREAD

**Issue by hopefullamp** [keyteki/keyteki#2894] opened 2022-11-01 16:38 UTC
When I build an alliance deck with this deck in TCO, Dark Aember Vault appears eventhough my deck has no Dark Aember Vault as a 13rd sanctum card. 

* This deck 
https://decksofkeyforge.com/decks/582e4b06-87bb-4429-9d60-ee2bce7c9a24

* Bug deck (alliance) - Image link 
https://postimg.cc/t1SpVwrD

* original alliance deck (DOK) 
https://decksofkeyforge.com/theoretical-decks/23a85c7f-3830-4842-a623-d65358345509

I want you to fix it. The original deck before merging into the Alliance from the TCO is normal. But after putting it together, there's a problem. also I tried deleting and rebuilding an alliance deck on TCO, but Same bug occurs.

**Comment by hopefullamp** [comment] 2022-11-02 23:32
I found why bug has been occured. 

Below deck is what I used for building alliance. 
https://decksofkeyforge.com/decks/0595c44d-d352-4b9a-99bd-fa9a93114e9d

If I use this deck's 'shadow' with 'other deck's sactum', bug is occured. Cause this decks' Dark Aember Vault is moved to other deck's sactum, But I couldnt find a bug with other Dark Aember Vault deck eventhough I tried with other Dark Aember Vault deck. 

Fix it please.

**Comment by romanogit** [comment] 2022-11-10 13:10
Possible similar to https://github.com/keyteki/keyteki/issues/2875

**Comment by romanogit** [comment] 2023-10-03 04:06
Dupe of https://github.com/keyteki/keyteki/issues/2875

**Closed by romanogit** 2023-10-03 04:06 UTC
Labels: bug, alliance
