### ISSUE TITLE
Unable to add a deck from a previous expansion

### ISSUE THREAD

**Issue by jonk5** [keyteki/keyteki#1691] opened 2020-07-13 15:54 UTC
The deck (AOA): [https://www.keyforgegame.com/deck-details/eb1d0c11-3a36-4106-a5f2-e0a9778c0882](https://www.keyforgegame.com/deck-details/eb1d0c11-3a36-4106-a5f2-e0a9778c0882)

Error message:
![image](https://user-images.githubusercontent.com/10610920/87325542-249ea680-c564-11ea-977d-b07f4360fb34.png)

Logs:
![image](https://user-images.githubusercontent.com/10610920/87325481-15b7f400-c564-11ea-9270-53659dcba2a0.png)

**Comment by romanogit** [comment] 2020-07-17 04:19
This is a problem with your local development server, right? I suggest you try the discard channel to discuss dev environment issues.

**Comment by romanogit** [comment] 2020-07-20 14:04
Closing. Unable to Reproduce.

**Closed by romanogit** 2020-07-20 14:04 UTC
Labels: unable to reproduce
