### ISSUE TITLE
Bellatoran Warrior not presenting captured amber, wards, etc.

### ISSUE THREAD

**Issue by Brampus** [keyteki/keyteki#3465] opened 2023-08-20 17:12 UTC
I played a game against Andyforge and with Shattered Throne I fought with four of my six bellatoran warrior token creatures, however, when they "captured" the amber, the effect took place, but no amber was seen on any of the warriors, making it impossible to tell what warriors had amber and what warriors did not.
-Brampus

**Comment by romanogit** [comment] 2023-08-21 12:04
This is fixed in https://github.com/keyteki/keyteki/pull/3457 , waiting review and deploy

**Comment by romanogit** [comment] 2023-08-21 12:04
Dupe of #3454

**Closed by romanogit** 2023-08-21 12:04 UTC
