### ISSUE TITLE
Multiple copies of Sir Marrows capture same AEmber multiple times.

### ISSUE THREAD

**Issue by morkaphene** [keyteki/keyteki#405] opened 2019-09-01 01:45 UTC
For example, if I have 3 Sir Marrows and my opponent reaps once, each Sir Marrows will capture 1 AEmber (so 3 captured total instead of just 1).

**Comment by 4ugeistr** [comment] 2019-09-03 08:27
Duplicate of #190

**Comment by cryogen** [comment] 2019-09-03 09:10
Thanks this is indeed a duplicate

**Closed by cryogen** 2019-09-03 09:10 UTC
