### ISSUE TITLE
Ixxyxli Fixfinger’s +1 Armor effect doesn’t impact Collector Worm

### ISSUE THREAD

**Issue by Megawats40** [keyteki/keyteki#1471] opened 2020-05-15 14:34 UTC
Fixfinger's effect should be for all Mars Creatures. Collector Worm is a Mars Creature. The fact that it's a Beast shouldn't exclude -- in the same way Scientists, or Agents aren't excluded.

**Comment by romanogit** [comment] 2020-05-15 14:44
Probably same root cause as #1459

**Comment by romanogit** [comment] 2020-05-16 14:09
![image](https://user-images.githubusercontent.com/2104075/82121719-8bbafd00-9765-11ea-9cf8-2fedb16895b8.png)

It says each "Martian" creature. Martian is a trait.

![image](https://user-images.githubusercontent.com/2104075/82121729-9d9ca000-9765-11ea-9459-a3b636cb2f95.png)

Collector Worm is a Beast and does not the Martian trait.

The card is working as expected.

Compare with Mars Needs Amber

![image](https://user-images.githubusercontent.com/2104075/82121749-b7d67e00-9765-11ea-8c22-91f469fb28d5.png)

It says Mars to mention the House.

Closing...

**Closed by romanogit** 2020-05-16 14:09 UTC
