### ISSUE TITLE
Song of the wild didn't work with these creatures:

### ISSUE THREAD

**Issue by VKChiuselli** [keyteki/keyteki#1141] opened 2020-02-20 16:39 UTC
Kangaphant
Mab the Mad.
They just give 1 aember instead of 2

**Comment by Tilbo** [comment] 2020-03-09 12:40
Also, Bramble Lynx.
![image](https://user-images.githubusercontent.com/53436024/76213643-05cd8380-6203-11ea-87ae-49540cecdb09.png)

**Comment by romanogit** [comment] 2020-09-09 14:18
Dupe of #1125

**Closed by romanogit** 2020-09-09 14:18 UTC
