### ISSUE TITLE
Interdimensional Graft vs. Vaultkeeper

### ISSUE THREAD

**Issue by Strikeforce007** [keyteki/keyteki#319] opened 2019-08-10 18:07 UTC
My opponent had Vaultkeeper on the battle-line and after playing Interdimensional Graft their Aember did not transfer to me. Unless I am mistaken since Interdimensional Graft does not indicate it is stealing the Aember I believe Vaultkeeper should not have stopped the transfer of Aember from their side to mine.

**Comment by Achocholacek** [comment] 2019-08-10 18:57
This is a known bug and a fix is incoming.

Similar/Dupe of #288

**Closed by Achocholacek** 2019-08-10 18:57 UTC
Labels: bug, duplicate
