### ISSUE TITLE
Professor Sutterkin + Bloodshard Imp

### ISSUE THREAD

**Issue by heiligeremilius** [keyteki/keyteki#149] opened 2019-07-28 20:26 UTC
After reaping with Sutterkin when Bloodsharp Imp is out, he is sacrificed without triggering the Reap - Effect (draw cards)

**Comment by cryogen** [comment] 2019-07-29 08:09
@jeremylarner Do you have a rules opinion on this?

I'm probably wrong but I think this sounds like it's working as intended

**Comment by jeremylarner** [comment] 2019-07-29 09:41
It should let the active player choose which to resolve first, but the player needs to have 'Prompt to order simultaneous effects' ticked in settings

**Comment by cryogen** [comment] 2019-07-29 10:01
Ah of course, I keep forgetting about that setting.

Seems like more of these timing issues show up with AoA, maybe we should revisit how we do this.

Closing this as invalid in the mean time as it's working as intended.

**Closed by cryogen** 2019-07-29 10:01 UTC
Labels: invalid
