### ISSUE TITLE
5C077 Can use itself (but it shouldn't)

### ISSUE THREAD

**Issue by UltimoFox** [keyteki/keyteki#2618] opened 2021-05-17 22:46 UTC
Pretty much what the issue's name suggests. I noticed it a week ago but forgot to get a screenshot, this time I have a screenshot where my opponent chose not to abuse it, instead fighting into an elusive creature once to end the loop. But for the moment, 5C077 can trigger itself to ready and use whenever it reaps, whereas it should be "ANOTHER" friendly creature. Screenshot attached (and thanks for the effort you put into this site!):
![image](https://user-images.githubusercontent.com/47079472/118565443-16b04800-b76a-11eb-91fa-b4e1dae3434b.png)

**Comment by romanogit** [comment] 2021-05-17 23:39
Dupe of #2524

**Closed** 2021-05-17 23:40 UTC

**Comment by romanogit** [comment] 2021-05-18 13:25
By the way, the issue was solved today as well.
