### ISSUE TITLE
Foozle reap effect

### ISSUE THREAD

**Issue by mattcalibo** [keyteki/keyteki#239] opened 2019-08-02 03:09 UTC
Foozle doesn't get the extra 1 aember when reaping after an enemy creature was destroyed, based on play 12 hours ago XD

**Comment by Achocholacek** [comment] 2019-08-02 03:14
Thanks for reporting - this is a known issue that should be mostly fixed in short order!
(Duplicate of #223 )

**Closed by Achocholacek** 2019-08-02 03:14 UTC
Labels: bug, duplicate
