### ISSUE TITLE
[WC] CXO Taber - can use/play multiple cards instead of one

### ISSUE THREAD

**Issue by iisfet** [keyteki/keyteki#914] opened 2019-11-14 13:53 UTC
Hi,

The turn below was very strange, I guess it comes from the CXO Taber card (Vilain should be able tu play/use only one card from a non star allliance house but he used/played 4 cards)

House phase - Vilain
Vilain chooses staralliance   as their active house this turn
________________________________________
Main phase - Vilain
Vilain plays Sci. Officer Qincan
Vilain plays Commander Chan
Vilain plays Light of the Archons, gaining 1Æmber   attaching it to Snag
Vilain uses CXO Taber to reap with CXO Taber
Vilain uses CXO Taber to allow them to play or use one non staralliance   card   this turn
Vilain uses Greater Oxtet to make Greater Oxtetfight Tricerian Legionary
Vilain uses Snag to make Snag fight Draco Praeco
Vilain uses Snag to apply a lasting effect
Vilain uses Buzzle to make Buzzle fight Snag
isfet uses Snag to remove its ward token
Vilain uses Seismo-entangler to stop dis  creatures from reaping next turn
Vilain plays Quant
________________________________________
Ready phase - Vilain
Vilain readies all of their cards  
________________________________________
Draw phase - Vilain
Vilain draws 4 cards   up to their maximum hand size of 6
________________________________________
End of turn 7
Vilain: 2 Æmber   isfet: 5 Æmber  

Thanks for your work

**Comment by hydrophilic-attack** [comment] 2019-11-15 23:40
This happened to me today. I reaped with the CXO and used an off-house card, yet I was still allowed to play and use more off-house cards

**Comment by romanogit** [comment] 2019-11-18 14:57
I wonder if it was the same root cause as #929

**Comment by romanogit** [comment] 2019-11-20 21:18
Fixed by #931

**Closed by romanogit** 2019-11-20 21:18 UTC
