### ISSUE TITLE
Omnipus and witch of the dawn

### ISSUE THREAD

**Issue by albo95** [keyteki/keyteki#2428] opened 2021-04-16 12:55 UTC
When i played Omnipus it discarded 16 cards instead of 8 and didn't played any tentacled discarded in this way. Also the play effect of witch of the dawn doesn't apply. Anyway thank you for all your work :)

**Comment by SkyJedi** [comment] 2021-04-16 13:31
witch is a dupe of #2426

**Comment by cryogen** [comment] 2021-04-18 09:57
Reopening as it's still broken. The counter is now correct, but it's still an array so you need to do .length on it

**Comment by SkyJedi** [comment] 2021-04-18 12:05
#2487

**Comment by romanogit** [comment] 2021-04-20 10:50
Deployed

**Closed by romanogit** 2021-04-20 10:50 UTC
Labels: Pending Deploy
