### ISSUE TITLE
Tribune Pompitus + Pale into Insignificance May not be working right

### ISSUE THREAD

**Issue by shadowfrillz** [keyteki/keyteki#3382] opened 2023-06-28 01:32 UTC
Scenario
My opponent had Tribune Pompitus out and had a few amber on Grey Rider (Base 2, +2 for each amber x2 = 6)
I played Pale into insignificance and TCO prompted me to kill Grey Rider even though I had a 2 power token creature on the board. This happened twice as I played 2 Pales back to back.

**Comment by strib** [comment] 2023-06-28 05:16
Strange!  Pale Into Insignificance shouldn't be prompting for anything -- it just straight up destroys everything with the lowest power, with no prompting.  Could there have been some other effect in play that required picking an enemy creature after destruction  (like a Fish being destroyed, for example)?

**Comment by shadowfrillz** [comment] 2023-06-28 10:58
My opponent and I tried to figure out what was going on but I you make a
very good point. If you're seeing that interaction work then they're
probably was we just didn't catch it... If that's the case sorry for the
false alarm!

**Comment by strib** [comment] 2023-06-28 14:31
No worries!  If you have links for the two decks that were playing, feel free to post them here, maybe I can figure something out from them.  Otherwise, if you see it happen again, please copy the full game log so we can check it out in detail. Thanks!

**Comment by shadowfrillz** [comment] 2023-06-28 17:09
Ha! Typically I log every game and of course in this case I did not... I'll
play the deck again and watch for something up with Pale.

**Comment by romanogit** [comment] 2023-10-16 02:34
let us know in case the issue is still occurring, closing for now.

**Closed by romanogit** 2023-10-16 02:34 UTC
