### ISSUE TITLE
duplicate chota hazri

### ISSUE THREAD

**Issue by skrohmagnon** [keyteki/keyteki#144] opened 2019-07-28 19:40 UTC
my opponent play murkens and play my chota hazri. After i don't remenber why it goes back to my hand and was still in the deck ...
![duplicate chota](https://user-images.githubusercontent.com/46242885/62011980-47338600-b180-11e9-8fa1-cc2802eb826c.JPG)

**Comment by Achocholacek** [comment] 2019-07-28 23:25
Duplicate of #138 and #127 - Should be resolved in next code push. Thanks for reporting!

**Closed by Achocholacek** 2019-07-28 23:25 UTC
