### ISSUE TITLE
house of maverik is hidden by label "Hand (6)"

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2389] opened 2021-04-08 12:29 UTC
i was in sealed mode, and i didnt notice i had maleficorn maverik in Saurian du to "Hand (6)" label

![image](https://user-images.githubusercontent.com/57572496/114026480-93e8c300-9876-11eb-9745-3573df0d43c4.png)

**Comment by SkyJedi** [comment] 2021-04-08 13:42
Dupe of #577

**Closed** 2021-04-08 13:44 UTC
