### ISSUE TITLE
Gargantugaun 

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#890] opened 2019-11-13 00:10 UTC
IT is leaving amber on my opponent's creatures, and not taking it from the player pool when a steal effect is going off. Looks like it is coming from the common pool.

**Comment by Osarek** [comment] 2019-11-15 20:24
duplicate  with #831

**Comment by Osarek** [comment] 2019-11-16 09:17
duplicate with #831 ?

**Comment by romanogit** [comment] 2019-11-20 23:26
Duplicate of #831. It is a capture problem at the moment.

**Closed by romanogit** 2019-11-20 23:26 UTC
