### ISSUE TITLE
Favor of Rex on opponent's charette should capture from opponent rather than from active player

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1106] opened 2020-01-23 20:29 UTC
If I play Favor of Rex on my opponent's charette (or any other Play: capture X creature) the amber that goes on that creature should not come from me but from my opponent.

We know this from the FAQ entry in the rules for replicator vs opponent's Sequis

In the Favor of Rex scenario, the same would happen. If I had just played Charette, it would have captured 3 from my oppnent.

A transcript of the game log is attached
[favor of rex charette.txt](https://github.com/keyteki/keyteki/files/4105296/favor.of.rex.charette.txt)

**Comment by jtrussell** [comment] 2020-01-24 16:20
Thanks for the report and game log, @hydrophilic-attack. You're correct that the Charette should have captured from your opponent, this is a known bug 😅.

Duplicate of #1031 
Related to #662

**Comment by cryogen** [comment] 2020-01-24 16:21
Closing as a duplicate

**Comment by romanogit** [comment] 2020-01-24 16:24
I think even though it is the same card, the propblem related to Restringutus might be a different fix than the one related to Charette. Charette involves capture which seems a bit more difficult to fix that, eventually, Restringutus.

The problem is not Favor of Rex, but how the targetted cards are implemented. 

I would leave this one opened

**Comment by jtrussell** [comment] 2020-01-24 16:28
Ah - fair point, @romanogit. And #1031 also mentions capturing but maybe that belongs in a different thread.

**Comment by cryogen** [comment] 2020-01-24 16:29
Regardless the issues are now linked, feel free to flesh out the other one with the real problem

**Closed** 2020-01-24 16:29 UTC
