### ISSUE TITLE
x2 Harbinger of Doom crashed the game

### ISSUE THREAD

**Issue by RaspberryEyes** [keyteki/keyteki#785] opened 2019-11-09 15:54 UTC
I had x2 Harbinger of Doom in play on my side, opponent had to Brobnar creatures on theirs.  They chose Saurian, began the turn by warding their two creatures, and then played Stomp to destroy one of the Harbingers (which according to the rules I believe would wipe out the ward tokens, but would kill my other Harbinger, which would then take out the Brobnar creatures and would destroy the board).  Well, it did take out everything, but I have attached what happened on screen as well, which caused both of us to disconnect and we were not able to finish the game.  And this dialog box went on FOREVER.  Thanks for all you guys do!

<img width="306" alt="Screen Shot 2019-11-09 at 9 43 51 AM" src="https://user-images.githubusercontent.com/57567609/68531358-e6ffc480-02d6-11ea-8a42-d5f9bcbb92df.png">

**Comment by cryogen** [comment] 2019-11-10 08:56
duplicate of #781

**Closed by cryogen** 2019-11-10 08:56 UTC
