### ISSUE TITLE
New Set Starting turn play

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#711] opened 2019-11-08 14:45 UTC

**Comment by romanogit** [comment] 2019-11-08 16:16
What is the issue here?

**Comment by romanogit** [comment] 2019-11-08 16:18
Is this the same as #712?

**Comment by KeyforgeJupiter** [comment] 2019-11-08 16:21
Yeah I think it copied it lol
But on my first turns it is making me discard everything. Wont let me play a card.

Sent from Mail for Windows 10

**Comment by cryogen** [comment] 2019-11-08 16:42
Duplicate of #712

**Closed by cryogen** 2019-11-08 16:42 UTC
