### ISSUE TITLE
Maverick throwing stars in Logos showing as shadows card. https://www.keyforgegame.com/deck-details/6acaaee6-db02-4f56-8667-0fd7666b7578

### ISSUE THREAD

**Issue by CalumSLZ** [keyteki/keyteki#115] opened 2019-07-28 12:19 UTC

**Comment by cryogen** [comment] 2019-07-28 12:20
Thanks for reporting.  This is a duplicate of #96 so I will close this one

**Closed by cryogen** 2019-07-28 12:20 UTC
