### ISSUE TITLE
Issue with Jargogle and Healing Blast (underneath)

### ISSUE THREAD

**Issue by Ciqala** [keyteki/keyteki#354] opened 2019-08-20 10:16 UTC
Opponent played jargogle with healing blast placed underneath, he attacked my 4 power brobnar creature causing 2 damage, his jargogle then showed 4 damage, healing blast was played when jargogle was destroyed which then healed jargogle for 4 damage even though he is a 2 power creature and gained 2 extra aember. 

in the same game the jargogle was able to play swindle (an alpha card) when destroyed and on another turn the jargogle was stunned and the opponent played smite (ready and fight) to remove the stun and was still able to fight with the jargogle when it should have been exhausted.

<img width="1064" alt="Screenshot 2019-08-20 at 00 30 20" src="https://user-images.githubusercontent.com/125326/63338245-59957f80-c33a-11e9-8e15-14e43d4d7baf.png">

**Comment by hydrophilic-attack** [comment] 2019-08-25 11:49
I think the situation you describe above with Healing Blast is the interaction working as intended. Jargogle's destroyed ability to play Healing Blast will resolve before he leaves play. At that point, he will have 4 damage on him from the fight which can be healed by healing blast. He is still destroyed despite being healed and will leave play, but he WAS healed for 4 damage, so the 2 bonus amber will proc. A creature having 2 power doesn't mean that it can't take more than 2 damage. It only means that 2 damage is enough for it to be destroyed, but if what destroys him deals 4 damage, he will still technically have 4 damage on him before he leaves play. The other things you describe sound like bugs though.

**Comment by romanogit** [comment] 2021-06-28 22:41
Jargogle's issues are now fixed
The Healing Blast seems a very specific corner case and general agreement is that it can heal the 4 damage

**Closed by romanogit** 2021-06-28 22:41 UTC
Labels: rules question
