### ISSUE TITLE
Nirbor Flamewing Tokenization

### ISSUE THREAD

**Issue by CatMarrow** [keyteki/keyteki#3943] opened 2024-05-08 02:25 UTC
Nirbor Flamewing fails to trigger at the start of the players turn if it entered the discard by being destroyed when it was a token creature.  This seem consistently replicable from my testing.

**Comment by strib** [comment] 2024-05-08 02:28
Thanks, though this is a duplicate of #3491 (and #3483).

**Closed by strib** 2024-05-08 02:28 UTC
