### ISSUE TITLE
Science needs to be reworked.

### ISSUE THREAD

**Issue by anxiospirate** [keyteki/keyteki#2517] opened 2021-04-21 06:49 UTC
I have had a few issues with science over the last couple of days. Science seems to be giving me an aember during the play effect of an action card. The wording for science! is gain an aember after you play an action card. Situations where this is significant is cards like dataforge and honors keysis. Players should not get their aember until after the cards effect has been resolved.
![I shouldn't have forged](https://user-images.githubusercontent.com/67936915/115509163-7594b580-a2c1-11eb-95bb-e039bae48080.PNG)

**Comment by blinkingline** [comment] 2021-04-21 16:45
[Science!](https://archonarcana.com/Science!) creates a [lasting effect](https://archonarcana.com/Lasting_effects) that resolves "after another action card is played".  This effect should resolve in the same window of the [Timing Chart](https://archonarcana.com/Timing_Chart#Play.2C_Discard.2C_or_Use_cards) as other **Play:** and "after a card is played" or "after a card enters play" effects.  As with any other point at which multiple abilities are available to be resolved, the order of the resolution of these effects is determined by the Active Player.

**Comment by romanogit** [comment] 2021-04-21 18:42
Reference from the timing chart:
![image](https://user-images.githubusercontent.com/2104075/115604769-21d19e80-a2b8-11eb-8997-eec9fce3e029.png)
Closing as working as intended

**Closed by romanogit** 2021-04-21 18:42 UTC
Labels: rules question

**Comment by anxiospirate** [comment] 2021-04-21 22:56
Man I hate FFG ruling. By comprehension this makes no sense but I sure.
Does this mean I get to choose the order of effects?

**Comment by blinkingline** [comment] 2021-04-22 00:42
Yes, if you have "Prompt for simultaneous abilities" turned on, you should be able to order the effects.
