### ISSUE TITLE
Gabos Longarms ignores Elusive on attack

### ISSUE THREAD

**Issue by cdenlin** [keyteki/keyteki#385] opened 2019-08-26 21:28 UTC
Opponent had Gabos Longarms. I had three Elusive creatures (Streke, Gold Key Imp, Lamindra) and Pip Pip.

By my reading of the Elusive rules, when Gabos fights an Elusive creature, the player can pick a target other than the defender for dealing damage. Elusive says "the first time this creature is attacked, no damage is dealt." The damage Gabos deals with its Before Fight effect is the damage it would deal to the Elusive creature.  
[Gabos_interaction.txt](https://github.com/keyteki/keyteki/files/3543170/Gabos_interaction.txt)
![Gabos_interaction](https://user-images.githubusercontent.com/54557258/63724888-822be680-c81e-11e9-9c53-6f49454e8b42.png)

**Comment by cryogen** [comment] 2019-08-27 10:28
From here: https://keyforge-compendium.com/sets/1-cota/cards/86-gabos-longarms (and from the confirmation from Brad) this seems to be working as intended

**Comment by Achocholacek** [comment] 2019-09-04 20:11
As per today's rule update - this is no longer an issue and Gabos would deal damage despite initially targeting an elusive creature. Closing.

**Closed by Achocholacek** 2019-09-04 20:11 UTC
Labels: wontfix
