### ISSUE TITLE
problem with The Callipygian Ideal

### ISSUE THREAD

**Issue by neotheone23** [keyteki/keyteki#955] opened 2019-11-19 15:18 UTC
there is a bug with The Callipygian Ideal. If it's on a creature, eg Praefectus Ludo, and there is aember on every of my creatures, i can use every aember on those creatures, eg to forge a key. but, i guess, i am only allowed to use it on the creature i put this card on

**Comment by cryogen** [comment] 2019-11-19 15:35
Thanks for reporting.  This is a duplicate of #937

**Closed by cryogen** 2019-11-19 15:35 UTC
