### ISSUE TITLE
Stir Up Trouble on Brend + keyfrog(+1) does not use stealed amber to forge with keyfrog

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2624] opened 2021-05-20 10:20 UTC
Opponent has 6amber 
I have 5 amber

on my board [Brend the fanatic](https://archonarcana.com/Brend_the_Fanatic) and [keyforg](https://archonarcana.com/Keyfrog) with +1 power

When i play (Stir Up Trouble)[https://archonarcana.com/Stir_Up_Trouble] to select Brend then keyfrog  (the selecting order does not matter)
i was expecting : 
Destroyed : steal 3,  (so 8 amber) and then destroyed : forge a key at current cost
But was : 
only Steal 3, no forging

Note if i have 6amber before playing Stir Up Trouble, i can steal and forge (and select order with prompt)

Before play Stir Up Trouble : 
![image](https://user-images.githubusercontent.com/57572496/118961076-36ab5b80-b964-11eb-9b55-61668ff40b4b.png)
After play Stir Up Trouble :
![image](https://user-images.githubusercontent.com/57572496/118961092-3b700f80-b964-11eb-9d3a-c23d7c4dac12.png)

game log : 
Osarek brings Baronne Foreman to The Crucible
osarek2 brings The Sargent that Nullifies Demolition to The Crucible
Compare Decks
osarek2 won the flip and is first player
 Osarek has connected to the game server
 osarek2 has connected to the game server
Osarek is shuffling their deck
Osarek draws 6 card  s to their maximum of 6
osarek2 is shuffling their deck
osarek2 draws 6 card  s to their maximum of 6
osarek2 draws 1 card 
Key phase - osarek2
osarek2 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - osarek2
 Osarek is attempting to switch manual mode on
 osarek2 is attempting to switch manual mode on
 Osarek allows enabling manual mode
 osarek2 switches manual mode on
 osarek2 allows enabling manual mode
 Osarek switches manual mode on
 Osarek manually moves Keyfrog from their deck to their play area
 Osarek manually moves Brend the Fanatic from their deck to their play area
 Osarek adds a damage to Keyfrog
 Osarek removes a damage from Keyfrog
 Osarek adds an power token to Keyfrog
 osarek2 sets Æmber  to 1 ( +1 )
 osarek2 sets Æmber  to 2 ( +1 )
 osarek2 sets Æmber  to 3 ( +1 )
 osarek2 sets Æmber  to 4 ( +1 )
 osarek2 sets Æmber  to 5 ( +1 )
 osarek2 sets Æmber  to 6 ( +1 )
 Osarek manually moves Stir Up Trouble from their deck to their hand
 Osarek has disconnected. The game will wait up to 30 seconds for them to reconnect
osarek2 chooses logos  as their active house this turn
Main phase - osarek2
 Osarek has reconnected
 Osarek has connected to the game server
Ready phase - osarek2
Draw phase - osarek2
 osarek2 declares Check!
End of turn 1
Osarek: 0 Æmber  (0 keys) osarek2: 6 Æmber  (0 keys)
TURN 1 - Osarek
Key phase - Osarek
Osarek does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Osarek
 Osarek switches manual mode off
 Osarek has disconnected. The game will wait up to 30 seconds for them to reconnect
 Osarek has reconnected
 Osarek has connected to the game server
Osarek chooses shadows  as their active house this turn
Main phase - Osarek
 Osarek has disconnected. The game will wait up to 30 seconds for them to reconnect
 Osarek has reconnected
 Osarek has connected to the game server
 osarek2 is attempting to switch manual mode on
 Osarek allows enabling manual mode
 osarek2 switches manual mode on
 Osarek sets Æmber  to 1 ( +1 )
 Osarek sets Æmber  to 2 ( +1 )
 Osarek sets Æmber  to 3 ( +1 )
 Osarek sets Æmber  to 4 ( +1 )
 Osarek sets Æmber  to 5 ( +1 )
 Osarek switches manual mode off
Osarek plays Stir Up Trouble
Osarek uses Stir Up Trouble to deal 3 damage to Brend the Fanatic
Osarek uses Brend the Fanatic to steal 3 Æmber  from osarek2
 Osarek is attempting to switch manual mode on

**Comment by romanogit** [comment] 2021-05-20 14:27
Same root cause as 
https://github.com/keyteki/keyteki/issues/2279

**Comment by Osarek** [comment] 2021-05-21 08:44
ok so should i close this one?

**Comment by romanogit** [comment] 2021-05-21 11:50
Closing, copied the description to the other issue

**Closed by romanogit** 2021-05-21 11:50 UTC
