### ISSUE TITLE
Quintrino flux doesn't destroy cards with the same power if target is warded

### ISSUE THREAD

**Issue by TeaSeaLancs** [keyteki/keyteki#899] opened 2019-11-13 15:00 UTC
During a game, I had the following setup:

My board: 6-power creature (warded), 5-power creature
Opponent's board: 3x 6-power creatures, 5-power creature, 4-power creature

I played Quintrino Flux, targetting my 6-power creature (warded) and the opponent's 4-power creature. The 4-power creature was destroyed, and my 6-power creature was unwarded, however none of the opponent's 6-power creatures were destroyed.

The text of the card reads:
> Play: Choose a friendly creature and an enemy creature. Destroy the chosen creatures and each creature with the same power as either of the chosen creatures.

I don't believe that the destruction of "each creature with the same power as either of the chosen creatures" is contingent on the targetted creature with that power level having been destroyed based on that text, so I think this is a bug? :P

**Comment by romanogit** [comment] 2019-11-14 02:59
![image](https://user-images.githubusercontent.com/2104075/68823107-063c8000-0650-11ea-90f4-7e3bec4d2fca.png)

**Comment by romanogit** [comment] 2019-11-14 03:14
I added a new test case and I am unable to reproduce this issue.

**Comment by TeaSeaLancs** [comment] 2019-11-21 16:12
Fair play, must be more to it :)

**Comment by romanogit** [comment] 2019-12-20 17:36
I was able to replicate this in #1032 . Closing this one as a dupe.

**Closed by romanogit** 2019-12-20 17:36 UTC
Labels: unable to reproduce
