### ISSUE TITLE
Fandangle readying Artifacts?

### ISSUE THREAD

**Issue by unzinc** [keyteki/keyteki#1704] opened 2020-07-13 20:35 UTC
Played SPike Trap and it entered ready. Only explaination I think is Fandangle

![image](https://user-images.githubusercontent.com/46981693/87351072-16299e00-c516-11ea-8b30-421c96950363.png)

**Comment by romanogit** [comment] 2020-07-13 20:37
Dupe of #1692 Closing to work on the other one

**Closed by romanogit** 2020-07-13 20:37 UTC
