### ISSUE TITLE
Horizon Saber with 2 bottom parts

### ISSUE THREAD

**Issue by Ciampone** [keyteki/keyteki#4393] opened 2024-11-25 14:48 UTC
I was playing a game and couldn't play my Horizon Saber because I'm with two bottom parts. I manually put both of the cards on the field and took a print
![error](https://github.com/user-attachments/assets/8e9d4ad0-81d3-49a9-a351-e1ed7ad0f385)

**Comment by strib** [comment] 2024-11-25 15:14
Thanks.  This is a duplicate of #4382 and the fix is just waiting on a new deployment to the servers.

**Closed by strib** 2024-11-25 15:14 UTC

**Comment by strib** [comment] 2024-11-25 20:07
(It's deployed now.)
