### ISSUE TITLE
The Grey Rider, Ready and Reap

### ISSUE THREAD

**Issue by jog1118** [keyteki/keyteki#263] opened 2019-08-03 04:44 UTC
The Grey Rider whean readying a creature, without an enemy to fight, doesnt allow reaping

**Comment by Achocholacek** [comment] 2019-08-03 20:14
Can you remember board state at all? I can't reproduce this.

Is there a chance you readied a non-sanctum creature when you played TGR? You would not be able to reap with them in that instance.

**Comment by jog1118** [comment] 2019-08-04 01:24
I'm sorry. I'm really not sure if it was a non-sanctum creature. Yes i
understand that if it was not a sanctum, you really couldnt reap with it ;)

**Comment by 4ugeistr** [comment] 2019-08-06 01:16
I've tested this and can confirm it works fine.

Right now, if there's no valid target or you got Foggified, you 
- can Reap if the "Readied to Fight" creature is of an active house.
- cannot Reap if the "Readied to Fight" creature is of a non-active house.

This is the correct behaviour.

**Comment by Achocholacek** [comment] 2019-08-07 21:23
thanks for the follow up @4ugeistr - I'm going to close this for now. @jog1118 - if it pops back up, let us know!

**Closed by Achocholacek** 2019-08-07 21:23 UTC
Labels: unable to reproduce
