### ISSUE TITLE
Murkens

### ISSUE THREAD

**Issue by nsalaway** [keyteki/keyteki#138] opened 2019-07-28 16:53 UTC
I played Murkens which played Pip Pip from my opponent's deck. Seemed to work okay for my turn, but on my opponents turn it returned to my opponent's hand. We did some manual stuff to put it on the board and it kept bugging out in various ways like preventing draw from my opponent while still being on the board.

**Comment by cryogen** [comment] 2019-07-28 18:21
Duplicate of #127 

Thanks for reporting!

**Closed by cryogen** 2019-07-28 18:21 UTC
