### ISSUE TITLE
Universal keylock/data forge - key cost not decreased the turn it is destroyed?

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#1021] opened 2019-12-06 01:53 UTC
Turn 13
Key phase - saluk
Beren uses Keyforgery to make saluk name house logos
Keyforgery reveals Memory Chip
Beren uses Keyforgery to continue opponent's Forge Key step
saluk forges the blue key , paying 9 Æmber
saluk uses Universal Keylock to destroy itself

^ - at this point, the key cost should go down to 6

House phase - saluk
saluk chooses staralliance as their active house this turn
Main phase - saluk
saluk uses Commander Chan to reap with Commander Chan
saluk uses Commander Chan to use Yantzee Gang
saluk uses Yantzee Gang to steal 1 Æmber from Beren
saluk uses First Officer Frane to reap with First Officer Frane
saluk uses First Officer Frane to capture 1 Æmber from Beren, placing it on Commander Chan
saluk uses First Officer Frane to deal 2 damage to Hugger-Mugger
saluk uses Com. Officer Kirby to reap with Com. Officer Kirby
saluk uses Com. Officer Kirby to allow them to play one non staralliance artifact, upgrade, or action​ card this turn
saluk uses Chief Engineer Walls to reap with Chief Engineer Walls
saluk uses Chief Engineer Walls to return C.Æ.N.D.L.E. Unit to their hand
saluk plays Tautau Vapors
saluk uses Tautau Vapors to draw 2 cards and archive 1 card
saluk plays Lay of the Land, gaining 1 Æmber
saluk uses Lay of the Land to look at the top 3 cards of their deck, rearrange them in any order, and draw 1 card
saluk plays Com. Officer Kirby
saluk uses Com. Officer Kirby to allow them to play one non staralliance artifact, upgrade, or action​ card this turn
saluk plays Data Forge, gaining 1 Æmber 

^ - at this point (after gaining the bonus aember from data forge) I have: 10 aember, and 6 cards in my hand. Current key cost should be 6, so 6+10-6 should be enough to forge a key, but it didn't let me.

Keyforgery was also in play, so it was still a gamble. I would have had to guess that correctly. But I wasn't given the option.

<img width="1118" alt="Screen Shot 2019-12-05 at 5 52 21 PM" src="https://user-images.githubusercontent.com/54372/70288939-1b588a80-1788-11ea-9ff1-064806df64ab.png">

**Comment by romanogit** [comment] 2021-02-23 18:59
Possibly related to #2261

**Comment by romanogit** [comment] 2021-06-02 15:02
Added one more manual test case to prove this is working as expected.

**Comment by romanogit** [comment] 2021-06-02 15:03
it is a pitty the screenshot did not capture the key cost bottom part

**Comment by romanogit** [comment] 2021-06-30 13:55
Closing as unable to reproduce for more than an year

**Closed by romanogit** 2021-06-30 13:55 UTC
Labels: unable to reproduce
