### ISSUE TITLE
Showing modified power and armor

### ISSUE THREAD

**Issue by LittleScorpion3** [keyteki/keyteki#1470] opened 2020-05-15 10:01 UTC
Is it possible to show modified power and armor due to bonuses during the game? Because i.e. when I use Self-Bolstering Automata I always have to remember how many power counters it has and I usually forget it.

**Comment by drallieiv** [comment] 2020-05-21 02:58
TCO behaves the way Keyforge is supposed to. Counter are only added when the card effects states to add counter.

When Self-Bolstering Automata is destroyed and saved by it's effect, it should receive the 2 "+1 power counter"

Permanent effects that adds power or armor should not be shown as counters/tokens.
But TCO could add a popup showing the computed values.

**Comment by drallieiv** [comment] 2020-05-21 02:59
Automata not getting counter looks like a duplicate of  #1469

**Comment by SkyJedi** [comment] 2020-05-21 03:10
It's on the list!

**Comment by LittleScorpion3** [comment] 2020-05-21 09:18
@drallieiv Yes, I agree. The fact is no +1 power counter were shown as well, so I had this SBA and can't remember if its Power was 3 or 5 or 7 ecc... My hope is to see a creature with i.e. 8 Power and 5 Armor and the possibility of clicking on the Power or the Armor to see all the "+X from *card name*" details.

**Comment by SkyJedi** [comment] 2020-10-26 21:17
i think this is done now

**Closed by SkyJedi** 2020-10-26 21:17 UTC
