### ISSUE TITLE
"Selective Preservation"

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2456] opened 2021-04-17 08:41 UTC
"Selective Preservation" only allows you to select creatures that share a power with another creature, which makes sense, because there's no point having to select a creature if it is the only creature of that power on the board.  However, because the creatures that do not share a power with another creature are not selected, they are also destroyed along with the creatures that have a shared power, that were also not chosen.

**Comment by SkyJedi** [comment] 2021-04-17 11:22
Dupe of #2434

**Closed by SkyJedi** 2021-04-17 11:22 UTC
